/********************************************************************************
** Form generated from reading UI file 'shortcutsform.ui'
**
** Created by: Qt User Interface Compiler version 5.13.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_SHORTCUTSFORM_H
#define UI_SHORTCUTSFORM_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QScrollArea>
#include <QtWidgets/QTreeWidget>
#include <QtWidgets/QVBoxLayout>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_shortcutsForm
{
public:
    QWidget *scrollAreaWidgetContents;
    QVBoxLayout *verticalLayout;
    QTreeWidget *treeWidget;

    void setupUi(QScrollArea *shortcutsForm)
    {
        if (shortcutsForm->objectName().isEmpty())
            shortcutsForm->setObjectName(QString::fromUtf8("shortcutsForm"));
        shortcutsForm->setWindowModality(Qt::NonModal);
        shortcutsForm->resize(963, 870);
        shortcutsForm->setWidgetResizable(true);
        scrollAreaWidgetContents = new QWidget();
        scrollAreaWidgetContents->setObjectName(QString::fromUtf8("scrollAreaWidgetContents"));
        scrollAreaWidgetContents->setGeometry(QRect(0, 0, 961, 868));
        verticalLayout = new QVBoxLayout(scrollAreaWidgetContents);
        verticalLayout->setObjectName(QString::fromUtf8("verticalLayout"));
        verticalLayout->setContentsMargins(0, 0, 0, 0);
        treeWidget = new QTreeWidget(scrollAreaWidgetContents);
        QFont font;
        font.setBold(true);
        font.setWeight(75);
        QTreeWidgetItem *__qtreewidgetitem = new QTreeWidgetItem(treeWidget);
        __qtreewidgetitem->setFont(0, font);
        new QTreeWidgetItem(__qtreewidgetitem);
        new QTreeWidgetItem(__qtreewidgetitem);
        new QTreeWidgetItem(__qtreewidgetitem);
        new QTreeWidgetItem(__qtreewidgetitem);
        new QTreeWidgetItem(__qtreewidgetitem);
        new QTreeWidgetItem(__qtreewidgetitem);
        new QTreeWidgetItem(__qtreewidgetitem);
        new QTreeWidgetItem(__qtreewidgetitem);
        new QTreeWidgetItem(__qtreewidgetitem);
        new QTreeWidgetItem(__qtreewidgetitem);
        new QTreeWidgetItem(__qtreewidgetitem);
        new QTreeWidgetItem(__qtreewidgetitem);
        new QTreeWidgetItem(__qtreewidgetitem);
        QTreeWidgetItem *__qtreewidgetitem1 = new QTreeWidgetItem(treeWidget);
        __qtreewidgetitem1->setFont(0, font);
        new QTreeWidgetItem(__qtreewidgetitem1);
        new QTreeWidgetItem(__qtreewidgetitem1);
        new QTreeWidgetItem(__qtreewidgetitem1);
        new QTreeWidgetItem(__qtreewidgetitem1);
        new QTreeWidgetItem(__qtreewidgetitem1);
        new QTreeWidgetItem(__qtreewidgetitem1);
        new QTreeWidgetItem(__qtreewidgetitem1);
        new QTreeWidgetItem(__qtreewidgetitem1);
        new QTreeWidgetItem(__qtreewidgetitem1);
        new QTreeWidgetItem(__qtreewidgetitem1);
        new QTreeWidgetItem(__qtreewidgetitem1);
        new QTreeWidgetItem(__qtreewidgetitem1);
        new QTreeWidgetItem(__qtreewidgetitem1);
        new QTreeWidgetItem(__qtreewidgetitem1);
        new QTreeWidgetItem(__qtreewidgetitem1);
        QTreeWidgetItem *__qtreewidgetitem2 = new QTreeWidgetItem(treeWidget);
        __qtreewidgetitem2->setFont(0, font);
        new QTreeWidgetItem(__qtreewidgetitem2);
        new QTreeWidgetItem(__qtreewidgetitem2);
        new QTreeWidgetItem(__qtreewidgetitem2);
        new QTreeWidgetItem(__qtreewidgetitem2);
        new QTreeWidgetItem(__qtreewidgetitem2);
        new QTreeWidgetItem(__qtreewidgetitem2);
        new QTreeWidgetItem(__qtreewidgetitem2);
        new QTreeWidgetItem(__qtreewidgetitem2);
        new QTreeWidgetItem(__qtreewidgetitem2);
        new QTreeWidgetItem(__qtreewidgetitem2);
        QTreeWidgetItem *__qtreewidgetitem3 = new QTreeWidgetItem(__qtreewidgetitem2);
        new QTreeWidgetItem(__qtreewidgetitem3);
        new QTreeWidgetItem(__qtreewidgetitem3);
        new QTreeWidgetItem(__qtreewidgetitem3);
        new QTreeWidgetItem(__qtreewidgetitem3);
        new QTreeWidgetItem(__qtreewidgetitem3);
        new QTreeWidgetItem(__qtreewidgetitem3);
        new QTreeWidgetItem(__qtreewidgetitem3);
        new QTreeWidgetItem(__qtreewidgetitem3);
        new QTreeWidgetItem(__qtreewidgetitem2);
        new QTreeWidgetItem(__qtreewidgetitem2);
        new QTreeWidgetItem(__qtreewidgetitem2);
        QTreeWidgetItem *__qtreewidgetitem4 = new QTreeWidgetItem(treeWidget);
        __qtreewidgetitem4->setFont(0, font);
        new QTreeWidgetItem(__qtreewidgetitem4);
        new QTreeWidgetItem(__qtreewidgetitem4);
        new QTreeWidgetItem(__qtreewidgetitem4);
        new QTreeWidgetItem(__qtreewidgetitem4);
        new QTreeWidgetItem(__qtreewidgetitem4);
        new QTreeWidgetItem(__qtreewidgetitem4);
        new QTreeWidgetItem(__qtreewidgetitem4);
        new QTreeWidgetItem(__qtreewidgetitem4);
        QTreeWidgetItem *__qtreewidgetitem5 = new QTreeWidgetItem(treeWidget);
        __qtreewidgetitem5->setFont(0, font);
        new QTreeWidgetItem(__qtreewidgetitem5);
        new QTreeWidgetItem(__qtreewidgetitem5);
        new QTreeWidgetItem(__qtreewidgetitem5);
        new QTreeWidgetItem(__qtreewidgetitem5);
        new QTreeWidgetItem(__qtreewidgetitem5);
        new QTreeWidgetItem(__qtreewidgetitem5);
        new QTreeWidgetItem(__qtreewidgetitem5);
        QTreeWidgetItem *__qtreewidgetitem6 = new QTreeWidgetItem(treeWidget);
        __qtreewidgetitem6->setFont(0, font);
        new QTreeWidgetItem(__qtreewidgetitem6);
        new QTreeWidgetItem(__qtreewidgetitem6);
        new QTreeWidgetItem(__qtreewidgetitem6);
        new QTreeWidgetItem(__qtreewidgetitem6);
        new QTreeWidgetItem(__qtreewidgetitem6);
        new QTreeWidgetItem(__qtreewidgetitem6);
        new QTreeWidgetItem(__qtreewidgetitem6);
        QTreeWidgetItem *__qtreewidgetitem7 = new QTreeWidgetItem(__qtreewidgetitem6);
        new QTreeWidgetItem(__qtreewidgetitem7);
        new QTreeWidgetItem(__qtreewidgetitem7);
        new QTreeWidgetItem(__qtreewidgetitem7);
        new QTreeWidgetItem(__qtreewidgetitem7);
        new QTreeWidgetItem(__qtreewidgetitem7);
        new QTreeWidgetItem(__qtreewidgetitem7);
        QTreeWidgetItem *__qtreewidgetitem8 = new QTreeWidgetItem(treeWidget);
        __qtreewidgetitem8->setFont(0, font);
        new QTreeWidgetItem(__qtreewidgetitem8);
        new QTreeWidgetItem(__qtreewidgetitem8);
        new QTreeWidgetItem(__qtreewidgetitem8);
        new QTreeWidgetItem(__qtreewidgetitem8);
        QTreeWidgetItem *__qtreewidgetitem9 = new QTreeWidgetItem(treeWidget);
        __qtreewidgetitem9->setFont(0, font);
        new QTreeWidgetItem(__qtreewidgetitem9);
        new QTreeWidgetItem(__qtreewidgetitem9);
        new QTreeWidgetItem(__qtreewidgetitem9);
        new QTreeWidgetItem(__qtreewidgetitem9);
        new QTreeWidgetItem(__qtreewidgetitem9);
        new QTreeWidgetItem(__qtreewidgetitem9);
        new QTreeWidgetItem(__qtreewidgetitem9);
        new QTreeWidgetItem(__qtreewidgetitem9);
        QTreeWidgetItem *__qtreewidgetitem10 = new QTreeWidgetItem(treeWidget);
        new QTreeWidgetItem(__qtreewidgetitem10);
        treeWidget->setObjectName(QString::fromUtf8("treeWidget"));
        treeWidget->setFocusPolicy(Qt::NoFocus);
        treeWidget->setAlternatingRowColors(true);
        treeWidget->setIconSize(QSize(24, 24));
        treeWidget->setUniformRowHeights(true);
        treeWidget->setColumnCount(3);
        treeWidget->header()->setMinimumSectionSize(150);
        treeWidget->header()->setDefaultSectionSize(300);

        verticalLayout->addWidget(treeWidget);

        shortcutsForm->setWidget(scrollAreaWidgetContents);

        retranslateUi(shortcutsForm);

        QMetaObject::connectSlotsByName(shortcutsForm);
    } // setupUi

    void retranslateUi(QScrollArea *shortcutsForm)
    {
        shortcutsForm->setWindowTitle(QCoreApplication::translate("shortcutsForm", "Winnow Shortcuts", nullptr));
        QTreeWidgetItem *___qtreewidgetitem = treeWidget->headerItem();
        ___qtreewidgetitem->setText(2, QCoreApplication::translate("shortcutsForm", "Comment", nullptr));
        ___qtreewidgetitem->setText(1, QCoreApplication::translate("shortcutsForm", "Shortcut", nullptr));
        ___qtreewidgetitem->setText(0, QCoreApplication::translate("shortcutsForm", "Category", nullptr));

        const bool __sortingEnabled = treeWidget->isSortingEnabled();
        treeWidget->setSortingEnabled(false);
        QTreeWidgetItem *___qtreewidgetitem1 = treeWidget->topLevelItem(0);
        ___qtreewidgetitem1->setText(0, QCoreApplication::translate("shortcutsForm", "File Operations", nullptr));
        QTreeWidgetItem *___qtreewidgetitem2 = ___qtreewidgetitem1->child(0);
        ___qtreewidgetitem2->setText(2, QCoreApplication::translate("shortcutsForm", "This is the letter \"O\", not zero", nullptr));
        ___qtreewidgetitem2->setText(1, QCoreApplication::translate("shortcutsForm", "O", nullptr));
        ___qtreewidgetitem2->setText(0, QCoreApplication::translate("shortcutsForm", "Open Folder", nullptr));
        QTreeWidgetItem *___qtreewidgetitem3 = ___qtreewidgetitem1->child(1);
        ___qtreewidgetitem3->setText(1, QCoreApplication::translate("shortcutsForm", "Opt/Alt + F5", nullptr));
        ___qtreewidgetitem3->setText(0, QCoreApplication::translate("shortcutsForm", "Refresh Current Folder", nullptr));
        QTreeWidgetItem *___qtreewidgetitem4 = ___qtreewidgetitem1->child(2);
        ___qtreewidgetitem4->setText(2, QCoreApplication::translate("shortcutsForm", "This is the letter \"O\", not zero", nullptr));
        ___qtreewidgetitem4->setText(1, QCoreApplication::translate("shortcutsForm", "Cmd/Ctrl + O", nullptr));
        ___qtreewidgetitem4->setText(0, QCoreApplication::translate("shortcutsForm", "Open USB Drive", nullptr));
        QTreeWidgetItem *___qtreewidgetitem5 = ___qtreewidgetitem1->child(3);
        ___qtreewidgetitem5->setText(2, QCoreApplication::translate("shortcutsForm", "This is the letter \"O\", not zero", nullptr));
        ___qtreewidgetitem5->setText(1, QCoreApplication::translate("shortcutsForm", "Opt/Alt + O", nullptr));
        ___qtreewidgetitem5->setText(0, QCoreApplication::translate("shortcutsForm", "Manage external programs", nullptr));
        QTreeWidgetItem *___qtreewidgetitem6 = ___qtreewidgetitem1->child(4);
        ___qtreewidgetitem6->setText(2, QCoreApplication::translate("shortcutsForm", "Open selected images in photoshop for example", nullptr));
        ___qtreewidgetitem6->setText(1, QCoreApplication::translate("shortcutsForm", "Opt/Alt + 0 - 9", nullptr));
        ___qtreewidgetitem6->setText(0, QCoreApplication::translate("shortcutsForm", "Open with external program", nullptr));
        QTreeWidgetItem *___qtreewidgetitem7 = ___qtreewidgetitem1->child(5);
        ___qtreewidgetitem7->setText(2, QCoreApplication::translate("shortcutsForm", "Copy images to another folder", nullptr));
        ___qtreewidgetitem7->setText(1, QCoreApplication::translate("shortcutsForm", "Q", nullptr));
        ___qtreewidgetitem7->setText(0, QCoreApplication::translate("shortcutsForm", "Ingest Picked Images", nullptr));
        QTreeWidgetItem *___qtreewidgetitem8 = ___qtreewidgetitem1->child(6);
        ___qtreewidgetitem8->setText(2, QCoreApplication::translate("shortcutsForm", "Toggles", nullptr));
        ___qtreewidgetitem8->setText(1, QCoreApplication::translate("shortcutsForm", "Cmd/Ctrl +  J", nullptr));
        ___qtreewidgetitem8->setText(0, QCoreApplication::translate("shortcutsForm", "Combine Raw+Jpg", nullptr));
        QTreeWidgetItem *___qtreewidgetitem9 = ___qtreewidgetitem1->child(7);
        ___qtreewidgetitem9->setText(2, QCoreApplication::translate("shortcutsForm", "Show images in all subfolders as well", nullptr));
        ___qtreewidgetitem9->setText(1, QCoreApplication::translate("shortcutsForm", "B", nullptr));
        ___qtreewidgetitem9->setText(0, QCoreApplication::translate("shortcutsForm", "Include subfolders", nullptr));
        QTreeWidgetItem *___qtreewidgetitem10 = ___qtreewidgetitem1->child(8);
        ___qtreewidgetitem10->setText(1, QCoreApplication::translate("shortcutsForm", "Cmd/Ctrl + R", nullptr));
        ___qtreewidgetitem10->setText(0, QCoreApplication::translate("shortcutsForm", "Open in Explorer or Finder", nullptr));
        QTreeWidgetItem *___qtreewidgetitem11 = ___qtreewidgetitem1->child(9);
        ___qtreewidgetitem11->setText(2, QCoreApplication::translate("shortcutsForm", "Use to update folders, for example when insert USB drive", nullptr));
        ___qtreewidgetitem11->setText(1, QCoreApplication::translate("shortcutsForm", "Opt/Alt + R", nullptr));
        ___qtreewidgetitem11->setText(0, QCoreApplication::translate("shortcutsForm", "Refresh Folders", nullptr));
        QTreeWidgetItem *___qtreewidgetitem12 = ___qtreewidgetitem1->child(10);
        ___qtreewidgetitem12->setText(2, QCoreApplication::translate("shortcutsForm", "Show only drives in Folders panel", nullptr));
        ___qtreewidgetitem12->setText(1, QCoreApplication::translate("shortcutsForm", "Opt/Alt + C", nullptr));
        ___qtreewidgetitem12->setText(0, QCoreApplication::translate("shortcutsForm", "Collapse Folders", nullptr));
        QTreeWidgetItem *___qtreewidgetitem13 = ___qtreewidgetitem1->child(11);
        ___qtreewidgetitem13->setText(2, QCoreApplication::translate("shortcutsForm", "Show geeky extract of metadata from file (error reporting)", nullptr));
        ___qtreewidgetitem13->setText(1, QCoreApplication::translate("shortcutsForm", "Cmd/Ctrl + Opt/Alt + Shift + M", nullptr));
        ___qtreewidgetitem13->setText(0, QCoreApplication::translate("shortcutsForm", "Report metadata", nullptr));
        QTreeWidgetItem *___qtreewidgetitem14 = ___qtreewidgetitem1->child(12);
        ___qtreewidgetitem14->setText(1, QCoreApplication::translate("shortcutsForm", "Cmd/Ctrl + Q", nullptr));
        ___qtreewidgetitem14->setText(0, QCoreApplication::translate("shortcutsForm", "Quit Winnow", nullptr));
        QTreeWidgetItem *___qtreewidgetitem15 = treeWidget->topLevelItem(1);
        ___qtreewidgetitem15->setText(0, QCoreApplication::translate("shortcutsForm", "Select, Pick, Classify and Filter", nullptr));
        QTreeWidgetItem *___qtreewidgetitem16 = ___qtreewidgetitem15->child(0);
        ___qtreewidgetitem16->setText(1, QCoreApplication::translate("shortcutsForm", "Cmd/Ctrl + A", nullptr));
        ___qtreewidgetitem16->setText(0, QCoreApplication::translate("shortcutsForm", "Select All", nullptr));
        QTreeWidgetItem *___qtreewidgetitem17 = ___qtreewidgetitem15->child(1);
        ___qtreewidgetitem17->setText(1, QCoreApplication::translate("shortcutsForm", "Cmd/Ctrl + Shift +A", nullptr));
        ___qtreewidgetitem17->setText(0, QCoreApplication::translate("shortcutsForm", "Invert Selection", nullptr));
        QTreeWidgetItem *___qtreewidgetitem18 = ___qtreewidgetitem15->child(2);
        ___qtreewidgetitem18->setText(1, QCoreApplication::translate("shortcutsForm", "R", nullptr));
        ___qtreewidgetitem18->setText(0, QCoreApplication::translate("shortcutsForm", "Refine", nullptr));
        QTreeWidgetItem *___qtreewidgetitem19 = ___qtreewidgetitem15->child(3);
        ___qtreewidgetitem19->setText(2, QCoreApplication::translate("shortcutsForm", "Toggles (grave accent)", nullptr));
        ___qtreewidgetitem19->setText(1, QCoreApplication::translate("shortcutsForm", "`", nullptr));
        ___qtreewidgetitem19->setText(0, QCoreApplication::translate("shortcutsForm", "Pick Image", nullptr));
        QTreeWidgetItem *___qtreewidgetitem20 = ___qtreewidgetitem15->child(4);
        ___qtreewidgetitem20->setText(2, QCoreApplication::translate("shortcutsForm", "Toggles alternate shortcut", nullptr));
        ___qtreewidgetitem20->setText(1, QCoreApplication::translate("shortcutsForm", "P", nullptr));
        ___qtreewidgetitem20->setText(0, QCoreApplication::translate("shortcutsForm", "Pick Image", nullptr));
        QTreeWidgetItem *___qtreewidgetitem21 = ___qtreewidgetitem15->child(5);
        ___qtreewidgetitem21->setText(2, QCoreApplication::translate("shortcutsForm", "Toggles alternate shortcut", nullptr));
        ___qtreewidgetitem21->setText(1, QCoreApplication::translate("shortcutsForm", "Mouse side button", nullptr));
        ___qtreewidgetitem21->setText(0, QCoreApplication::translate("shortcutsForm", "Pick Image", nullptr));
        QTreeWidgetItem *___qtreewidgetitem22 = ___qtreewidgetitem15->child(6);
        ___qtreewidgetitem22->setText(2, QCoreApplication::translate("shortcutsForm", "Undo each pick in reverse order to picking", nullptr));
        ___qtreewidgetitem22->setText(1, QCoreApplication::translate("shortcutsForm", "Cmd/Ctrl + Opt/Alt + Z", nullptr));
        ___qtreewidgetitem22->setText(0, QCoreApplication::translate("shortcutsForm", "Undo pick", nullptr));
        QTreeWidgetItem *___qtreewidgetitem23 = ___qtreewidgetitem15->child(7);
        ___qtreewidgetitem23->setText(2, QCoreApplication::translate("shortcutsForm", "Toggles", nullptr));
        ___qtreewidgetitem23->setText(1, QCoreApplication::translate("shortcutsForm", "Cmd/Ctrl + `", nullptr));
        ___qtreewidgetitem23->setText(0, QCoreApplication::translate("shortcutsForm", "Filter Picks", nullptr));
        QTreeWidgetItem *___qtreewidgetitem24 = ___qtreewidgetitem15->child(8);
        ___qtreewidgetitem24->setText(2, QCoreApplication::translate("shortcutsForm", "Toggles", nullptr));
        ___qtreewidgetitem24->setText(1, QCoreApplication::translate("shortcutsForm", "1 to 5", nullptr));
        ___qtreewidgetitem24->setText(0, QCoreApplication::translate("shortcutsForm", "Rate Image", nullptr));
        QTreeWidgetItem *___qtreewidgetitem25 = ___qtreewidgetitem15->child(9);
        ___qtreewidgetitem25->setText(2, QCoreApplication::translate("shortcutsForm", "Toggles", nullptr));
        ___qtreewidgetitem25->setText(1, QCoreApplication::translate("shortcutsForm", "Shift 1 to 5", nullptr));
        ___qtreewidgetitem25->setText(0, QCoreApplication::translate("shortcutsForm", "Filter on Rating", nullptr));
        QTreeWidgetItem *___qtreewidgetitem26 = ___qtreewidgetitem15->child(10);
        ___qtreewidgetitem26->setText(2, QCoreApplication::translate("shortcutsForm", "Toggles", nullptr));
        ___qtreewidgetitem26->setText(1, QCoreApplication::translate("shortcutsForm", "6 to 0", nullptr));
        ___qtreewidgetitem26->setText(0, QCoreApplication::translate("shortcutsForm", "Color Class", nullptr));
        QTreeWidgetItem *___qtreewidgetitem27 = ___qtreewidgetitem15->child(11);
        ___qtreewidgetitem27->setText(2, QCoreApplication::translate("shortcutsForm", "Toggles", nullptr));
        ___qtreewidgetitem27->setText(1, QCoreApplication::translate("shortcutsForm", "Shift 6 to 0", nullptr));
        ___qtreewidgetitem27->setText(0, QCoreApplication::translate("shortcutsForm", "Filter on Color Class", nullptr));
        QTreeWidgetItem *___qtreewidgetitem28 = ___qtreewidgetitem15->child(12);
        ___qtreewidgetitem28->setText(1, QCoreApplication::translate("shortcutsForm", "Shift + C", nullptr));
        ___qtreewidgetitem28->setText(0, QCoreApplication::translate("shortcutsForm", "Clear Filters", nullptr));
        QTreeWidgetItem *___qtreewidgetitem29 = ___qtreewidgetitem15->child(13);
        ___qtreewidgetitem29->setText(2, QCoreApplication::translate("shortcutsForm", "Toggles", nullptr));
        ___qtreewidgetitem29->setText(1, QCoreApplication::translate("shortcutsForm", "Shift + I", nullptr));
        ___qtreewidgetitem29->setText(0, QCoreApplication::translate("shortcutsForm", "Invert Filters", nullptr));
        QTreeWidgetItem *___qtreewidgetitem30 = ___qtreewidgetitem15->child(14);
        ___qtreewidgetitem30->setText(2, QCoreApplication::translate("shortcutsForm", "Toggles", nullptr));
        ___qtreewidgetitem30->setText(1, QCoreApplication::translate("shortcutsForm", "Shift + D", nullptr));
        ___qtreewidgetitem30->setText(0, QCoreApplication::translate("shortcutsForm", "Filter most recent day", nullptr));
        QTreeWidgetItem *___qtreewidgetitem31 = treeWidget->topLevelItem(2);
        ___qtreewidgetitem31->setText(0, QCoreApplication::translate("shortcutsForm", "Navigation", nullptr));
        QTreeWidgetItem *___qtreewidgetitem32 = ___qtreewidgetitem31->child(0);
        ___qtreewidgetitem32->setText(1, QCoreApplication::translate("shortcutsForm", "Right", nullptr));
        ___qtreewidgetitem32->setText(0, QCoreApplication::translate("shortcutsForm", "Next Image", nullptr));
        QTreeWidgetItem *___qtreewidgetitem33 = ___qtreewidgetitem31->child(1);
        ___qtreewidgetitem33->setText(2, QCoreApplication::translate("shortcutsForm", "When in Loupe view", nullptr));
        ___qtreewidgetitem33->setText(1, QCoreApplication::translate("shortcutsForm", "Mouse scroll wheel", nullptr));
        ___qtreewidgetitem33->setText(0, QCoreApplication::translate("shortcutsForm", "Next Image", nullptr));
        QTreeWidgetItem *___qtreewidgetitem34 = ___qtreewidgetitem31->child(2);
        ___qtreewidgetitem34->setText(1, QCoreApplication::translate("shortcutsForm", "Left", nullptr));
        ___qtreewidgetitem34->setText(0, QCoreApplication::translate("shortcutsForm", "Previous Image", nullptr));
        QTreeWidgetItem *___qtreewidgetitem35 = ___qtreewidgetitem31->child(3);
        ___qtreewidgetitem35->setText(2, QCoreApplication::translate("shortcutsForm", "When in Loupe view", nullptr));
        ___qtreewidgetitem35->setText(1, QCoreApplication::translate("shortcutsForm", "Mouse scroll whell", nullptr));
        ___qtreewidgetitem35->setText(0, QCoreApplication::translate("shortcutsForm", "Previous Image", nullptr));
        QTreeWidgetItem *___qtreewidgetitem36 = ___qtreewidgetitem31->child(4);
        ___qtreewidgetitem36->setText(1, QCoreApplication::translate("shortcutsForm", "Up", nullptr));
        ___qtreewidgetitem36->setText(0, QCoreApplication::translate("shortcutsForm", "Image Above", nullptr));
        QTreeWidgetItem *___qtreewidgetitem37 = ___qtreewidgetitem31->child(5);
        ___qtreewidgetitem37->setText(1, QCoreApplication::translate("shortcutsForm", "Down", nullptr));
        ___qtreewidgetitem37->setText(0, QCoreApplication::translate("shortcutsForm", "Image Below", nullptr));
        QTreeWidgetItem *___qtreewidgetitem38 = ___qtreewidgetitem31->child(6);
        ___qtreewidgetitem38->setText(1, QCoreApplication::translate("shortcutsForm", "Home", nullptr));
        ___qtreewidgetitem38->setText(0, QCoreApplication::translate("shortcutsForm", "First Image", nullptr));
        QTreeWidgetItem *___qtreewidgetitem39 = ___qtreewidgetitem31->child(7);
        ___qtreewidgetitem39->setText(1, QCoreApplication::translate("shortcutsForm", "End", nullptr));
        ___qtreewidgetitem39->setText(0, QCoreApplication::translate("shortcutsForm", "Last Image", nullptr));
        QTreeWidgetItem *___qtreewidgetitem40 = ___qtreewidgetitem31->child(8);
        ___qtreewidgetitem40->setText(1, QCoreApplication::translate("shortcutsForm", "Page Down", nullptr));
        ___qtreewidgetitem40->setText(0, QCoreApplication::translate("shortcutsForm", "Next Page of Thumbnails", nullptr));
        QTreeWidgetItem *___qtreewidgetitem41 = ___qtreewidgetitem31->child(9);
        ___qtreewidgetitem41->setText(1, QCoreApplication::translate("shortcutsForm", "Page Up", nullptr));
        ___qtreewidgetitem41->setText(0, QCoreApplication::translate("shortcutsForm", "Previous Page of Thumbnails", nullptr));
        QTreeWidgetItem *___qtreewidgetitem42 = ___qtreewidgetitem31->child(10);
        ___qtreewidgetitem42->setText(0, QCoreApplication::translate("shortcutsForm", "Scrolling", nullptr));
        QTreeWidgetItem *___qtreewidgetitem43 = ___qtreewidgetitem42->child(0);
        ___qtreewidgetitem43->setText(1, QCoreApplication::translate("shortcutsForm", "Opt/Alt + Left", nullptr));
        ___qtreewidgetitem43->setText(0, QCoreApplication::translate("shortcutsForm", "Scroll Left", nullptr));
        QTreeWidgetItem *___qtreewidgetitem44 = ___qtreewidgetitem42->child(1);
        ___qtreewidgetitem44->setText(1, QCoreApplication::translate("shortcutsForm", "Opt/Alt + Right", nullptr));
        ___qtreewidgetitem44->setText(0, QCoreApplication::translate("shortcutsForm", "Scroll Right", nullptr));
        QTreeWidgetItem *___qtreewidgetitem45 = ___qtreewidgetitem42->child(2);
        ___qtreewidgetitem45->setText(1, QCoreApplication::translate("shortcutsForm", "Opt/Alt + Up", nullptr));
        ___qtreewidgetitem45->setText(0, QCoreApplication::translate("shortcutsForm", "Scroll Up", nullptr));
        QTreeWidgetItem *___qtreewidgetitem46 = ___qtreewidgetitem42->child(3);
        ___qtreewidgetitem46->setText(1, QCoreApplication::translate("shortcutsForm", "Opt/Alt + Down", nullptr));
        ___qtreewidgetitem46->setText(0, QCoreApplication::translate("shortcutsForm", "Scroll Down", nullptr));
        QTreeWidgetItem *___qtreewidgetitem47 = ___qtreewidgetitem42->child(4);
        ___qtreewidgetitem47->setText(1, QCoreApplication::translate("shortcutsForm", "Cmd/Ctrl + Opt/Alt + Left", nullptr));
        ___qtreewidgetitem47->setText(0, QCoreApplication::translate("shortcutsForm", "Scroll Page Left", nullptr));
        QTreeWidgetItem *___qtreewidgetitem48 = ___qtreewidgetitem42->child(5);
        ___qtreewidgetitem48->setText(1, QCoreApplication::translate("shortcutsForm", "Cmd/Ctrl + Opt/Alt + Right", nullptr));
        ___qtreewidgetitem48->setText(0, QCoreApplication::translate("shortcutsForm", "Scroll Page Right", nullptr));
        QTreeWidgetItem *___qtreewidgetitem49 = ___qtreewidgetitem42->child(6);
        ___qtreewidgetitem49->setText(1, QCoreApplication::translate("shortcutsForm", "Cmd/Ctrl + Opt/Alt + Up", nullptr));
        ___qtreewidgetitem49->setText(0, QCoreApplication::translate("shortcutsForm", "Scroll Page Up", nullptr));
        QTreeWidgetItem *___qtreewidgetitem50 = ___qtreewidgetitem42->child(7);
        ___qtreewidgetitem50->setText(1, QCoreApplication::translate("shortcutsForm", "Cmd/Ctrl + Opt/Alt + Down", nullptr));
        ___qtreewidgetitem50->setText(0, QCoreApplication::translate("shortcutsForm", "Scroll Page Down", nullptr));
        QTreeWidgetItem *___qtreewidgetitem51 = ___qtreewidgetitem31->child(11);
        ___qtreewidgetitem51->setText(1, QCoreApplication::translate("shortcutsForm", "Cmd/Ctrl  Left", nullptr));
        ___qtreewidgetitem51->setText(0, QCoreApplication::translate("shortcutsForm", "Previous Pick", nullptr));
        QTreeWidgetItem *___qtreewidgetitem52 = ___qtreewidgetitem31->child(12);
        ___qtreewidgetitem52->setText(1, QCoreApplication::translate("shortcutsForm", "Cmd/Ctrl  Right", nullptr));
        ___qtreewidgetitem52->setText(0, QCoreApplication::translate("shortcutsForm", "Next Pick", nullptr));
        QTreeWidgetItem *___qtreewidgetitem53 = ___qtreewidgetitem31->child(13);
        ___qtreewidgetitem53->setText(1, QCoreApplication::translate("shortcutsForm", "Cmd/Ctrl + Shift + Right", nullptr));
        ___qtreewidgetitem53->setText(0, QCoreApplication::translate("shortcutsForm", "Random Image", nullptr));
        QTreeWidgetItem *___qtreewidgetitem54 = treeWidget->topLevelItem(3);
        ___qtreewidgetitem54->setText(0, QCoreApplication::translate("shortcutsForm", "Views", nullptr));
        QTreeWidgetItem *___qtreewidgetitem55 = ___qtreewidgetitem54->child(0);
        ___qtreewidgetitem55->setText(1, QCoreApplication::translate("shortcutsForm", "E   or   Enter", nullptr));
        ___qtreewidgetitem55->setText(0, QCoreApplication::translate("shortcutsForm", "Loupe View", nullptr));
        QTreeWidgetItem *___qtreewidgetitem56 = ___qtreewidgetitem54->child(1);
        ___qtreewidgetitem56->setText(1, QCoreApplication::translate("shortcutsForm", "G", nullptr));
        ___qtreewidgetitem56->setText(0, QCoreApplication::translate("shortcutsForm", "Grid View", nullptr));
        QTreeWidgetItem *___qtreewidgetitem57 = ___qtreewidgetitem54->child(2);
        ___qtreewidgetitem57->setText(1, QCoreApplication::translate("shortcutsForm", "T", nullptr));
        ___qtreewidgetitem57->setText(0, QCoreApplication::translate("shortcutsForm", "Table View", nullptr));
        QTreeWidgetItem *___qtreewidgetitem58 = ___qtreewidgetitem54->child(3);
        ___qtreewidgetitem58->setText(1, QCoreApplication::translate("shortcutsForm", "C", nullptr));
        ___qtreewidgetitem58->setText(0, QCoreApplication::translate("shortcutsForm", "Compare View", nullptr));
        QTreeWidgetItem *___qtreewidgetitem59 = ___qtreewidgetitem54->child(4);
        ___qtreewidgetitem59->setText(2, QCoreApplication::translate("shortcutsForm", "Toggles", nullptr));
        ___qtreewidgetitem59->setText(1, QCoreApplication::translate("shortcutsForm", "F", nullptr));
        ___qtreewidgetitem59->setText(0, QCoreApplication::translate("shortcutsForm", "Full Screen", nullptr));
        QTreeWidgetItem *___qtreewidgetitem60 = ___qtreewidgetitem54->child(5);
        ___qtreewidgetitem60->setText(1, QCoreApplication::translate("shortcutsForm", "Esc", nullptr));
        ___qtreewidgetitem60->setText(0, QCoreApplication::translate("shortcutsForm", "Exit Full Screen", nullptr));
        QTreeWidgetItem *___qtreewidgetitem61 = ___qtreewidgetitem54->child(6);
        ___qtreewidgetitem61->setText(2, QCoreApplication::translate("shortcutsForm", "Toggles", nullptr));
        ___qtreewidgetitem61->setText(1, QCoreApplication::translate("shortcutsForm", "I", nullptr));
        ___qtreewidgetitem61->setText(0, QCoreApplication::translate("shortcutsForm", "Show Information", nullptr));
        QTreeWidgetItem *___qtreewidgetitem62 = ___qtreewidgetitem54->child(7);
        ___qtreewidgetitem62->setText(2, QCoreApplication::translate("shortcutsForm", "Toggles", nullptr));
        ___qtreewidgetitem62->setText(1, QCoreApplication::translate("shortcutsForm", "Cmd/Ctrl + I", nullptr));
        ___qtreewidgetitem62->setText(0, QCoreApplication::translate("shortcutsForm", "Show Rating Badge", nullptr));
        QTreeWidgetItem *___qtreewidgetitem63 = treeWidget->topLevelItem(4);
        ___qtreewidgetitem63->setText(0, QCoreApplication::translate("shortcutsForm", "Zoom, Resize and Rotate", nullptr));
        QTreeWidgetItem *___qtreewidgetitem64 = ___qtreewidgetitem63->child(0);
        ___qtreewidgetitem64->setText(2, QCoreApplication::translate("shortcutsForm", "Opens zoom heads up display control ", nullptr));
        ___qtreewidgetitem64->setText(1, QCoreApplication::translate("shortcutsForm", "Z", nullptr));
        ___qtreewidgetitem64->setText(0, QCoreApplication::translate("shortcutsForm", "Zoom In/Out", nullptr));
        QTreeWidgetItem *___qtreewidgetitem65 = ___qtreewidgetitem63->child(1);
        ___qtreewidgetitem65->setText(1, QCoreApplication::translate("shortcutsForm", "+", nullptr));
        ___qtreewidgetitem65->setText(0, QCoreApplication::translate("shortcutsForm", "Incremental Zoom In", nullptr));
        QTreeWidgetItem *___qtreewidgetitem66 = ___qtreewidgetitem63->child(2);
        ___qtreewidgetitem66->setText(1, QCoreApplication::translate("shortcutsForm", "-", nullptr));
        ___qtreewidgetitem66->setText(0, QCoreApplication::translate("shortcutsForm", "Incremental Zoom Out", nullptr));
        QTreeWidgetItem *___qtreewidgetitem67 = ___qtreewidgetitem63->child(3);
        ___qtreewidgetitem67->setText(1, QCoreApplication::translate("shortcutsForm", "]", nullptr));
        ___qtreewidgetitem67->setText(0, QCoreApplication::translate("shortcutsForm", "Enlarge Thumbnails", nullptr));
        QTreeWidgetItem *___qtreewidgetitem68 = ___qtreewidgetitem63->child(4);
        ___qtreewidgetitem68->setText(1, QCoreApplication::translate("shortcutsForm", "[", nullptr));
        ___qtreewidgetitem68->setText(0, QCoreApplication::translate("shortcutsForm", "Shrink Thumbnails", nullptr));
        QTreeWidgetItem *___qtreewidgetitem69 = ___qtreewidgetitem63->child(5);
        ___qtreewidgetitem69->setText(1, QCoreApplication::translate("shortcutsForm", "Cmd/Ctrl + ]", nullptr));
        ___qtreewidgetitem69->setText(0, QCoreApplication::translate("shortcutsForm", "Rotate Image Clockwise", nullptr));
        QTreeWidgetItem *___qtreewidgetitem70 = ___qtreewidgetitem63->child(6);
        ___qtreewidgetitem70->setText(1, QCoreApplication::translate("shortcutsForm", "Cmd/Ctrl + [", nullptr));
        ___qtreewidgetitem70->setText(0, QCoreApplication::translate("shortcutsForm", "Rotate Image Counter Clockwise", nullptr));
        QTreeWidgetItem *___qtreewidgetitem71 = treeWidget->topLevelItem(5);
        ___qtreewidgetitem71->setText(0, QCoreApplication::translate("shortcutsForm", "Windows", nullptr));
        QTreeWidgetItem *___qtreewidgetitem72 = ___qtreewidgetitem71->child(0);
        ___qtreewidgetitem72->setText(2, QCoreApplication::translate("shortcutsForm", "3 way toggle (Focus > Hide < Show)", nullptr));
        ___qtreewidgetitem72->setText(1, QCoreApplication::translate("shortcutsForm", "F3", nullptr));
        ___qtreewidgetitem72->setText(0, QCoreApplication::translate("shortcutsForm", "Files Panel", nullptr));
        QTreeWidgetItem *___qtreewidgetitem73 = ___qtreewidgetitem71->child(1);
        ___qtreewidgetitem73->setText(2, QCoreApplication::translate("shortcutsForm", "3 way toggle (Focus > Hide < Show)", nullptr));
        ___qtreewidgetitem73->setText(1, QCoreApplication::translate("shortcutsForm", "F4", nullptr));
        ___qtreewidgetitem73->setText(0, QCoreApplication::translate("shortcutsForm", "Favourites Panel", nullptr));
        QTreeWidgetItem *___qtreewidgetitem74 = ___qtreewidgetitem71->child(2);
        ___qtreewidgetitem74->setText(2, QCoreApplication::translate("shortcutsForm", "3 way toggle (Focus > Hide < Show)", nullptr));
        ___qtreewidgetitem74->setText(1, QCoreApplication::translate("shortcutsForm", "F5", nullptr));
        ___qtreewidgetitem74->setText(0, QCoreApplication::translate("shortcutsForm", "Filters Panel", nullptr));
        QTreeWidgetItem *___qtreewidgetitem75 = ___qtreewidgetitem71->child(3);
        ___qtreewidgetitem75->setText(2, QCoreApplication::translate("shortcutsForm", "3 way toggle (Focus > Hide < Show)", nullptr));
        ___qtreewidgetitem75->setText(1, QCoreApplication::translate("shortcutsForm", "F6", nullptr));
        ___qtreewidgetitem75->setText(0, QCoreApplication::translate("shortcutsForm", "Metadata Panel", nullptr));
        QTreeWidgetItem *___qtreewidgetitem76 = ___qtreewidgetitem71->child(4);
        ___qtreewidgetitem76->setText(2, QCoreApplication::translate("shortcutsForm", "3 way toggle (Focus > Hide < Show)", nullptr));
        ___qtreewidgetitem76->setText(1, QCoreApplication::translate("shortcutsForm", "F7", nullptr));
        ___qtreewidgetitem76->setText(0, QCoreApplication::translate("shortcutsForm", "Thumbnails Panel", nullptr));
        QTreeWidgetItem *___qtreewidgetitem77 = ___qtreewidgetitem71->child(5);
        ___qtreewidgetitem77->setText(2, QCoreApplication::translate("shortcutsForm", "Toggles visibility", nullptr));
        ___qtreewidgetitem77->setText(1, QCoreApplication::translate("shortcutsForm", "F9", nullptr));
        ___qtreewidgetitem77->setText(0, QCoreApplication::translate("shortcutsForm", "Application Menu", nullptr));
        QTreeWidgetItem *___qtreewidgetitem78 = ___qtreewidgetitem71->child(6);
        ___qtreewidgetitem78->setText(2, QCoreApplication::translate("shortcutsForm", "Toggles visibility", nullptr));
        ___qtreewidgetitem78->setText(1, QCoreApplication::translate("shortcutsForm", "F10", nullptr));
        ___qtreewidgetitem78->setText(0, QCoreApplication::translate("shortcutsForm", "Application Statusbar", nullptr));
        QTreeWidgetItem *___qtreewidgetitem79 = ___qtreewidgetitem71->child(7);
        ___qtreewidgetitem79->setText(0, QCoreApplication::translate("shortcutsForm", "Show/Hide Panel TitleBars", nullptr));
        QTreeWidgetItem *___qtreewidgetitem80 = ___qtreewidgetitem79->child(0);
        ___qtreewidgetitem80->setText(2, QCoreApplication::translate("shortcutsForm", "Toggles", nullptr));
        ___qtreewidgetitem80->setText(1, QCoreApplication::translate("shortcutsForm", "Shift +F3", nullptr));
        ___qtreewidgetitem80->setText(0, QCoreApplication::translate("shortcutsForm", "Files Panel Titlebar", nullptr));
        QTreeWidgetItem *___qtreewidgetitem81 = ___qtreewidgetitem79->child(1);
        ___qtreewidgetitem81->setText(2, QCoreApplication::translate("shortcutsForm", "Toggles", nullptr));
        ___qtreewidgetitem81->setText(1, QCoreApplication::translate("shortcutsForm", "Shift +F4", nullptr));
        ___qtreewidgetitem81->setText(0, QCoreApplication::translate("shortcutsForm", "Favourites Panel Titlebar", nullptr));
        QTreeWidgetItem *___qtreewidgetitem82 = ___qtreewidgetitem79->child(2);
        ___qtreewidgetitem82->setText(2, QCoreApplication::translate("shortcutsForm", "Toggles", nullptr));
        ___qtreewidgetitem82->setText(1, QCoreApplication::translate("shortcutsForm", "Shift +F5", nullptr));
        ___qtreewidgetitem82->setText(0, QCoreApplication::translate("shortcutsForm", "Filters Panel Titlebar", nullptr));
        QTreeWidgetItem *___qtreewidgetitem83 = ___qtreewidgetitem79->child(3);
        ___qtreewidgetitem83->setText(2, QCoreApplication::translate("shortcutsForm", "Toggles", nullptr));
        ___qtreewidgetitem83->setText(1, QCoreApplication::translate("shortcutsForm", "Shift +F6", nullptr));
        ___qtreewidgetitem83->setText(0, QCoreApplication::translate("shortcutsForm", "Metadata Panel Titlebar", nullptr));
        QTreeWidgetItem *___qtreewidgetitem84 = ___qtreewidgetitem79->child(4);
        ___qtreewidgetitem84->setText(2, QCoreApplication::translate("shortcutsForm", "Toggles", nullptr));
        ___qtreewidgetitem84->setText(1, QCoreApplication::translate("shortcutsForm", "Shift +F7", nullptr));
        ___qtreewidgetitem84->setText(0, QCoreApplication::translate("shortcutsForm", "Thumbnails Panel Titlebar", nullptr));
        QTreeWidgetItem *___qtreewidgetitem85 = ___qtreewidgetitem79->child(5);
        ___qtreewidgetitem85->setText(2, QCoreApplication::translate("shortcutsForm", "Toggles", nullptr));
        ___qtreewidgetitem85->setText(1, QCoreApplication::translate("shortcutsForm", "Cmd/Ctrl + L", nullptr));
        ___qtreewidgetitem85->setText(0, QCoreApplication::translate("shortcutsForm", "All Panel Titlebars", nullptr));
        QTreeWidgetItem *___qtreewidgetitem86 = treeWidget->topLevelItem(6);
        ___qtreewidgetitem86->setText(0, QCoreApplication::translate("shortcutsForm", "Workspaces", nullptr));
        QTreeWidgetItem *___qtreewidgetitem87 = ___qtreewidgetitem86->child(0);
        ___qtreewidgetitem87->setText(1, QCoreApplication::translate("shortcutsForm", "Cmd/Ctrl + 0 to 9", nullptr));
        ___qtreewidgetitem87->setText(0, QCoreApplication::translate("shortcutsForm", "Select Workspace", nullptr));
        QTreeWidgetItem *___qtreewidgetitem88 = ___qtreewidgetitem86->child(1);
        ___qtreewidgetitem88->setText(1, QCoreApplication::translate("shortcutsForm", "W", nullptr));
        ___qtreewidgetitem88->setText(0, QCoreApplication::translate("shortcutsForm", "New Workspace", nullptr));
        QTreeWidgetItem *___qtreewidgetitem89 = ___qtreewidgetitem86->child(2);
        ___qtreewidgetitem89->setText(1, QCoreApplication::translate("shortcutsForm", "Cmd/Ctrl + W", nullptr));
        ___qtreewidgetitem89->setText(0, QCoreApplication::translate("shortcutsForm", "Manage Workspaces", nullptr));
        QTreeWidgetItem *___qtreewidgetitem90 = ___qtreewidgetitem86->child(3);
        ___qtreewidgetitem90->setText(1, QCoreApplication::translate("shortcutsForm", "Cmd/Ctrl + Shift +W", nullptr));
        ___qtreewidgetitem90->setText(0, QCoreApplication::translate("shortcutsForm", "Default Workspace", nullptr));
        QTreeWidgetItem *___qtreewidgetitem91 = treeWidget->topLevelItem(7);
        ___qtreewidgetitem91->setText(0, QCoreApplication::translate("shortcutsForm", "Slideshow", nullptr));
        QTreeWidgetItem *___qtreewidgetitem92 = ___qtreewidgetitem91->child(0);
        ___qtreewidgetitem92->setText(1, QCoreApplication::translate("shortcutsForm", "S", nullptr));
        ___qtreewidgetitem92->setText(0, QCoreApplication::translate("shortcutsForm", "Start", nullptr));
        QTreeWidgetItem *___qtreewidgetitem93 = ___qtreewidgetitem91->child(1);
        ___qtreewidgetitem93->setText(1, QCoreApplication::translate("shortcutsForm", "Esc", nullptr));
        ___qtreewidgetitem93->setText(0, QCoreApplication::translate("shortcutsForm", "Exit", nullptr));
        QTreeWidgetItem *___qtreewidgetitem94 = ___qtreewidgetitem91->child(2);
        ___qtreewidgetitem94->setText(2, QCoreApplication::translate("shortcutsForm", "Only while slideshow active", nullptr));
        ___qtreewidgetitem94->setText(1, QCoreApplication::translate("shortcutsForm", "1 - 9", nullptr));
        ___qtreewidgetitem94->setText(0, QCoreApplication::translate("shortcutsForm", "Change Delay Between Slides", nullptr));
        QTreeWidgetItem *___qtreewidgetitem95 = ___qtreewidgetitem91->child(3);
        ___qtreewidgetitem95->setText(2, QCoreApplication::translate("shortcutsForm", "Only while slideshow active (Toggles)", nullptr));
        ___qtreewidgetitem95->setText(1, QCoreApplication::translate("shortcutsForm", "W", nullptr));
        ___qtreewidgetitem95->setText(0, QCoreApplication::translate("shortcutsForm", "Wrap at end of folder", nullptr));
        QTreeWidgetItem *___qtreewidgetitem96 = ___qtreewidgetitem91->child(4);
        ___qtreewidgetitem96->setText(2, QCoreApplication::translate("shortcutsForm", "Toggles", nullptr));
        ___qtreewidgetitem96->setText(1, QCoreApplication::translate("shortcutsForm", "R", nullptr));
        ___qtreewidgetitem96->setText(0, QCoreApplication::translate("shortcutsForm", "Random / Sequential progress", nullptr));
        QTreeWidgetItem *___qtreewidgetitem97 = ___qtreewidgetitem91->child(5);
        ___qtreewidgetitem97->setText(1, QCoreApplication::translate("shortcutsForm", "Backspace", nullptr));
        ___qtreewidgetitem97->setText(0, QCoreApplication::translate("shortcutsForm", "Go back to previous random slide", nullptr));
        QTreeWidgetItem *___qtreewidgetitem98 = ___qtreewidgetitem91->child(6);
        ___qtreewidgetitem98->setText(1, QCoreApplication::translate("shortcutsForm", "Spacebar", nullptr));
        ___qtreewidgetitem98->setText(0, QCoreApplication::translate("shortcutsForm", "Pause / continue", nullptr));
        QTreeWidgetItem *___qtreewidgetitem99 = ___qtreewidgetitem91->child(7);
        ___qtreewidgetitem99->setText(1, QCoreApplication::translate("shortcutsForm", "H", nullptr));
        ___qtreewidgetitem99->setText(0, QCoreApplication::translate("shortcutsForm", "Display shortcuts during slideshow", nullptr));
        QTreeWidgetItem *___qtreewidgetitem100 = treeWidget->topLevelItem(8);
        ___qtreewidgetitem100->setText(0, QCoreApplication::translate("shortcutsForm", "Help", nullptr));
        QTreeWidgetItem *___qtreewidgetitem101 = ___qtreewidgetitem100->child(0);
        ___qtreewidgetitem101->setText(1, QCoreApplication::translate("shortcutsForm", "?", nullptr));
        ___qtreewidgetitem101->setText(0, QCoreApplication::translate("shortcutsForm", "Help document", nullptr));
        treeWidget->setSortingEnabled(__sortingEnabled);

    } // retranslateUi

};

namespace Ui {
    class shortcutsForm: public Ui_shortcutsForm {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_SHORTCUTSFORM_H
