#include "Utilities/modelstore.h"
#include "Dialogs/modeldownloaddlg.h"
#include "Main/global.h"

#include <QCoreApplication>
#include <QCryptographicHash>
#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QHash>
#include <QJsonDocument>
#include <QJsonObject>
#include <QMutex>
#include <QMutexLocker>
#include <QSaveFile>
#include <QSet>
#include <QStandardPaths>
#include <QStorageInfo>
#include <QWidget>

/*
    See Utilities/modelstore.h for the design: append-only versioned URLs, compiled-in
    hashes, and the <Models>/models.json sidecar that makes staleness an O(1) question.
*/

namespace ModelStore {

namespace {

/* ---------------------------------------------------------------------------------------
   THE CATALOG.  Generated by tools/gen_model_catalog.sh from the ReleaseExtras onnx files -- do
   not hand-edit the sizes or hashes.  Re-exporting a model means running that script,
   pasting the row it prints (which bumps `version`), and uploading <stem>-<version>.onnx
   ALONGSIDE the existing one.  Never overwrite a published file: builds already in the
   wild fetch the exact bytes they were compiled against.
   --------------------------------------------------------------------------------------- */
const QVector<ModelInfo> &table()
{
    static const QVector<ModelInfo> t = {
        { Model::FocusPoint,  "focus_point_model.onnx", "Pan to focus point", 1,
          11496441LL,  "1ad6a799589b4d1cbd22e0e7aab22cf07b7feffbcf521d0d5caee4f176d43ae3", true  },
        { Model::Pmrid,       "pmrid.onnx",             "Denoise raw",        1,
          4165323LL,   "d5b55f2a0a6da82fe1982bf70078f34268cf909161c256b8b60f3dd1c9019fd1", true  },
        { Model::U2Net,       "u2net.onnx",             "Select Subject",     1,
          175997641LL, "8d10d2f3bb75ae3b6d527c77944fc5e7dcd94b29809d47a739a7a728a912b491", false },
        { Model::SkySeg,      "skyseg.onnx",            "Select Sky",         1,
          175997079LL, "ab9c34c64c3d821220a2886a4a06da4642ffa14d5b30e8d5339056a089aa1d39", false },
        { Model::Midas,       "midas.onnx",             "Depth Range",        1,
          66764249LL,  "2d8c6cb8f415229daf1eb041024208e2608c9f98e17c81cc7c6ecb449c56fd58", false },
        { Model::Migan,       "migan.onnx",             "Spot Heal",          1,
          26639422LL,  "3aa5c7ac2e980c0a542703ce6fbd9497fadc176720c96af7bac55a56d1038d53", false },
        { Model::Lama,        "lama.onnx",              "Spot Heal",          1,
          208039155LL, "b6aecb7650fe83f11655964b9d7cb0df944990c8ef016c4a92e0ac8c709634dd", false },
        { Model::Sam2Encoder, "sam2_encoder.onnx",      "Object Mask",        1,
          134261315LL, "4cc015ee18520e93f8c7ddfeaca7436039daaaaf19721b4b96a8810a805e82f7", false },
        { Model::Sam2Decoder, "sam2_decoder.onnx",      "Object Mask",        1,
          20551111LL,  "f0e30257c95ffb64787018804fe2a96cf35e0ca873a05c4e7545ecb57a584395", false }
    };
    return t;
}

/* One lock covers the sidecar and the state cache; both are touched from render workers
   (through path()) as well as the GUI thread. */
QMutex g_mutex;

struct Record {                 // one line of models.json
    QString sha256;
    qint64  bytes = 0;
    qint64  mtime = 0;          // secsSinceEpoch, to spot a file changed behind our back
};

QHash<QString, Record> g_sidecar;
bool                   g_sidecarLoaded = false;

/* state() is called from the develop render paths, so it must not stat (let alone hash) on
   every call. Computed once per model per process; invalidated on download / remove. */
QHash<int, State> g_stateCache;

QString sidecarPath() { return QDir(dir()).filePath("models.json"); }

void loadSidecar()          // call with g_mutex held
{
    if (g_sidecarLoaded) return;
    g_sidecarLoaded = true;
    QFile f(sidecarPath());
    if (!f.open(QIODevice::ReadOnly)) return;
    const QJsonObject root = QJsonDocument::fromJson(f.readAll()).object();
    for (auto it = root.constBegin(); it != root.constEnd(); ++it) {
        const QJsonObject o = it.value().toObject();
        Record r;
        r.sha256 = o.value("sha256").toString();
        r.bytes  = qint64(o.value("bytes").toDouble());
        r.mtime  = qint64(o.value("mtime").toDouble());
        g_sidecar.insert(it.key(), r);
    }
}

void saveSidecar()          // call with g_mutex held
{
    QJsonObject root;
    for (auto it = g_sidecar.constBegin(); it != g_sidecar.constEnd(); ++it) {
        QJsonObject o;
        o.insert("sha256", it.value().sha256);
        o.insert("bytes",  double(it.value().bytes));
        o.insert("mtime",  double(it.value().mtime));
        root.insert(it.key(), o);
    }
    QSaveFile f(sidecarPath());
    if (!f.open(QIODevice::WriteOnly)) return;
    f.write(QJsonDocument(root).toJson(QJsonDocument::Indented));
    f.commit();
}

/* Streamed so a 198 MB model is never held in memory. */
QString hashFile(const QString &path)
{
    QFile f(path);
    if (!f.open(QIODevice::ReadOnly)) return QString();
    QCryptographicHash h(QCryptographicHash::Sha256);
    if (!h.addData(&f)) return QString();
    return QString::fromLatin1(h.result().toHex());
}

/* Where a model would live if it were bundled beside the binary. On macOS that is
   Winnow.app/Contents/MacOS (matching how ExifTool and the Winnets are laid out). */
QString bundledPath(const ModelInfo &mi)
{
    return QDir(QCoreApplication::applicationDirPath()).filePath(QString::fromLatin1(mi.fileName));
}

QString downloadedPath(const ModelInfo &mi)
{
    return QDir(dir()).filePath(QString::fromLatin1(mi.fileName));
}

State computeState(const ModelInfo &mi)     // call with g_mutex held
{
    /* The app dir wins. That resolves the two bundled models, and it keeps a dev tree
       that still has every .onnx beside the binary working exactly as before. */
    if (QFile::exists(bundledPath(mi))) return State::Bundled;
    if (mi.bundled) return State::Missing;          // should be impossible in a real build

    const QString p = downloadedPath(mi);
    QFileInfo fi(p);
    if (!fi.exists()) return State::Missing;

    loadSidecar();
    const QString key = QString::fromLatin1(mi.fileName);
    const Record  rec = g_sidecar.value(key);
    const qint64  mtime = fi.lastModified().toSecsSinceEpoch();

    /* Fast path: the sidecar vouches for this exact file, so trust its recorded hash
       rather than re-reading 198 MB. */
    if (!rec.sha256.isEmpty() && rec.bytes == fi.size() && rec.mtime == mtime)
        return rec.sha256 == QString::fromLatin1(mi.sha256) ? State::Ready : State::Stale;

    /* No provenance (or the file moved/changed): hash it once and record the answer. */
    const QString actual = hashFile(p);
    if (actual.isEmpty()) return State::Corrupt;

    Record fresh;
    fresh.sha256 = actual;
    fresh.bytes  = fi.size();
    fresh.mtime  = mtime;
    g_sidecar.insert(key, fresh);
    saveSidecar();

    if (actual == QString::fromLatin1(mi.sha256)) return State::Ready;

    /* Intact but not what this build wants -> an older export (Stale, offer an update).
       Hashes to neither -> genuinely damaged bytes (Corrupt, offer a repair). */
    if (!rec.sha256.isEmpty() && rec.sha256 != actual) return State::Corrupt;
    return State::Stale;
}

}   // namespace

const QVector<ModelInfo> &catalog() { return table(); }

const ModelInfo &info(Model m)
{
    for (const ModelInfo &mi : table())
        if (mi.id == m) return mi;
    Q_ASSERT_X(false, "ModelStore::info", "model not in catalog");
    return table().first();
}

QString url(Model m)
{
    /* APPEND-ONLY. The version in the filename is what lets a build fetch exactly the
       bytes it was compiled against, years after a newer Winnow started shipping
       different weights. Never repoint this at an unversioned name. */
    static const QString kBase = QStringLiteral("https://winnow.ca/winnow/models/");
    const ModelInfo &mi = info(m);
    QString stem = QString::fromLatin1(mi.fileName);
    stem.chop(5);                                   // drop ".onnx"
    return kBase + stem + "-" + QString::number(mi.version) + ".onnx";
}

QString dir()
{
    const QString d = QStandardPaths::writableLocation(QStandardPaths::AppDataLocation)
                      + "/Models";
    QDir().mkpath(d);
    return d;
}

State state(Model m)
{
    QMutexLocker lock(&g_mutex);
    const int key = int(m);
    if (g_stateCache.contains(key)) return g_stateCache.value(key);
    const State s = computeState(info(m));
    g_stateCache.insert(key, s);
    return s;
}

void invalidate(Model m)
{
    QMutexLocker lock(&g_mutex);
    g_stateCache.remove(int(m));
}

QString path(Model m)
{
    const State s = state(m);
    if (s != State::Ready && s != State::Bundled) return QString();
    const ModelInfo &mi = info(m);
    const QString b = bundledPath(mi);
    if (QFile::exists(b)) return b;
    return downloadedPath(mi);
}

bool isAvailable(Model m) { return !path(m).isEmpty(); }

bool isAvailable(const QVector<Model> &models)
{
    for (Model m : models)
        if (!isAvailable(m)) return false;
    return true;
}

QString stateText(State s)
{
    switch (s) {
    case State::Bundled: return QObject::tr("Included with Winnow");
    case State::Ready:   return QObject::tr("Downloaded");
    case State::Missing: return QObject::tr("Not downloaded");
    case State::Stale:   return QObject::tr("Update available");
    case State::Corrupt: return QObject::tr("Damaged - re-download");
    }
    return QString();
}

bool ensure(const QVector<Model> &need, QWidget *parent)
{
    if (G::isLogger) G::log("ModelStore::ensure");

    /* Never reach for the network during automated runs -- and test mode redirects
       AppDataLocation anyway, so the features no-op exactly as they do with a model
       absent. Mirrors MW::checkForUpdate's guard. */
    if (G::isTest || G::isStressTest || QStandardPaths::isTestModeEnabled()) return false;

    QVector<Model> want;
    for (Model m : need) {
        const State s = state(m);
        if (s != State::Ready && s != State::Bundled) want << m;
    }
    if (want.isEmpty()) return true;

    qint64 total = 0;
    for (Model m : want) total += info(m).bytes;

    /* Refuse up front rather than filling the disk and failing at the last chunk. */
    const QStorageInfo storage(dir());
    if (storage.isValid() && storage.bytesAvailable() > 0
        && storage.bytesAvailable() < total + (64LL << 20)) {
        ModelDownloadDlg::reportNoSpace(total, storage.bytesAvailable(), parent);
        return false;
    }

    ModelDownloadDlg dlg(want, parent);
    const bool ok = (dlg.exec() == QDialog::Accepted);

    for (Model m : want) invalidate(m);
    return ok && isAvailable(need);
}

QVector<QString> orphans()
{
    QSet<QString> known;
    for (const ModelInfo &mi : table()) known.insert(QString::fromLatin1(mi.fileName));

    QVector<QString> out;
    const QFileInfoList entries =
        QDir(dir()).entryInfoList(QStringList() << "*.onnx", QDir::Files);
    for (const QFileInfo &fi : entries)
        if (!known.contains(fi.fileName())) out << fi.fileName();
    return out;
}

qint64 orphanBytes()
{
    qint64 total = 0;
    const QDir d(dir());
    for (const QString &name : orphans()) total += QFileInfo(d.filePath(name)).size();
    return total;
}

bool remove(Model m)
{
    const ModelInfo &mi = info(m);
    if (mi.bundled) return false;                    // not ours to delete
    const QString key = QString::fromLatin1(mi.fileName);
    const bool ok = QFile::remove(downloadedPath(mi));
    QMutexLocker lock(&g_mutex);
    loadSidecar();
    g_sidecar.remove(key);
    saveSidecar();
    g_stateCache.remove(int(m));
    return ok;
}

qint64 bytesOnDisk()
{
    qint64 total = 0;
    const QFileInfoList entries =
        QDir(dir()).entryInfoList(QStringList() << "*.onnx", QDir::Files);
    for (const QFileInfo &fi : entries) total += fi.size();
    return total;
}

void sweepPartials()
{
    const QDir d(dir());
    const QFileInfoList entries = d.entryInfoList(QStringList() << "*.part", QDir::Files);
    for (const QFileInfo &fi : entries) QFile::remove(fi.absoluteFilePath());
}

/* Called by ModelDownloadDlg once a model has been verified onto disk, so the next
   state() sees it without a restart. */
void recordDownloaded(Model m, const QString &sha256)
{
    const ModelInfo &mi = info(m);
    QFileInfo fi(downloadedPath(mi));
    QMutexLocker lock(&g_mutex);
    loadSidecar();
    Record r;
    r.sha256 = sha256;
    r.bytes  = fi.size();
    r.mtime  = fi.lastModified().toSecsSinceEpoch();
    g_sidecar.insert(QString::fromLatin1(mi.fileName), r);
    saveSidecar();
    g_stateCache.remove(int(m));
}

}   // namespace ModelStore
