#ifndef FUSIONBASE_H
#define FUSIONBASE_H

#include <QObject>
#include <QString>
#include <QStringList>

class FusionBase : public QObject
{
    Q_OBJECT
public:
    explicit FusionBase(QObject *parent = nullptr) : QObject(parent) {}
    ~FusionBase() override = default;

    // Display name of the fusion method
    virtual QString name() const = 0;

    struct Options {
        bool align;
        bool alignFuse;
        bool focusMeasure;
        bool depthMap;
        bool fuse;
    };

    // imagePaths: full paths to input images (RAW, TIFF, JPG, etc)
    // outputFolder: folder to put final result (and any intermediates)
    // outputImagePath: full path of the fused image
    // generatedMaskPath: optional full path of mask generated by this fusion method
    virtual bool fuse(const QStringList &imagePaths,
                      const QString &outputFolder,
                      const Options &options) = 0;

signals:
    void updateStatus(bool keepBase, QString msg, QString src);
    void progress(QString stage, int current, int total);
};

#endif // FUSIONBASE_H
