#ifndef BASELINEEXPOSUREDATA_H
#define BASELINEEXPOSUREDATA_H

/*
    GENERATED by tools/gen_baseline_exposure.py -- do not edit by hand; re-run it
    over a folder holding a sample of any new body.

    Adobe's per-camera BaselineExposure (EV), read from DNGs that Adobe DNG Converter
    made of one sample per model, keyed on the DNG's UniqueCameraModel -- the same
    maker-prefixed key as Winnow's canonical camera model. See Develop/
    baselineexposure.h.
*/

namespace BaselineExposureData {

struct Entry { const char *model; float ev; };

constexpr Entry kTable[] = {
    {"Canon EOS 7D Mark II", -0.18f},
    {"Canon EOS R5", 0.39f},
    {"Canon EOS R6 Mark II", 0.34f},
    {"Fujifilm GFX 50S II", -0.01f},
    {"Fujifilm X-T2", 1.15f},
    {"Fujifilm X-T50", 1.02f},
    {"LEICA M10", -0.78f},
    {"Nikon D100", -0.75f},
    {"Nikon D2H", -0.75f},
    {"Nikon D7200", 0.35f},
    {"Nikon D800E", 0.35f},
    {"Nikon D810", 0.35f},
    {"Nikon D850", 0.35f},
    {"Nikon Z 9", 0.20f},
    {"OM Digital Solutions OM-1 Mark II", 0.37f},
    {"Olympus E-M1", 0.32f},
    {"Panasonic DC-GX9", 0.25f},
    {"Sony DSC-RX100", -0.25f},
    {"Sony ILCE-1", 0.15f},
    {"Sony ILCE-1M2", 0.15f},
    {"Sony ILCE-7RM2", 0.35f},
    {"Sony ILCE-7RM4", 0.35f},
    {"Sony ILCE-7RM5", 0.35f},
    {"Sony ILCE-9", 0.35f},
    {"Sony ILCE-9M3", 0.25f},
};

} // namespace BaselineExposureData

#endif // BASELINEEXPOSUREDATA_H
