#ifndef CAMERACURVEDATA_H
#define CAMERACURVEDATA_H

/*
    GENERATED by tools/gen_camera_curves.py -- do not edit by hand; re-run it.

    Per-maker average tone curves for the "Camera contrast" tone mapping, from the
    installed Adobe camera-matching profiles (each curve composed with its profile's
    BaselineExposureOffset, so x is scene-linear with 1.0 = sensor white). Sampled at
    x = (i/32)^2. See Develop/cameracurve.h for how they are used.
*/

namespace CameraCurveData {

constexpr int kSamples = 33;

struct Maker { const char *name; float y[kSamples]; };

/* Generic: mean of Canon, Nikon and Sony -- for any maker not listed below. */
constexpr float kGeneric[kSamples] = {
    0.0000f, 0.0008f, 0.0021f, 0.0047f, 0.0105f, 0.0213f, 0.0396f, 0.0661f, 0.1016f, 0.1453f, 0.1940f, 0.2459f, 0.3008f, 0.3579f, 0.4149f, 0.4711f, 0.5251f, 0.5762f, 0.6244f, 0.6707f, 0.7154f, 0.7563f, 0.7923f, 0.8252f, 0.8553f, 0.8817f, 0.9039f, 0.9229f, 0.9393f, 0.9537f, 0.9657f, 0.9753f, 0.9832f
};

constexpr Maker kMakers[] = {
    /* Canon: mean of 116 "Camera Standard" profiles */
    {"Canon", {0.0000f, 0.0007f, 0.0017f, 0.0042f, 0.0096f, 0.0199f, 0.0372f, 0.0629f, 0.0965f, 0.1392f, 0.1879f, 0.2419f, 0.2998f, 0.3598f, 0.4200f, 0.4792f, 0.5364f, 0.5903f, 0.6404f, 0.6868f, 0.7295f, 0.7691f, 0.8056f, 0.8389f, 0.8687f, 0.8947f, 0.9168f, 0.9360f, 0.9521f, 0.9662f, 0.9787f, 0.9884f, 0.9959f}},
    /* Nikon: mean of 84 "Camera Standard" profiles */
    {"Nikon", {0.0000f, 0.0008f, 0.0019f, 0.0042f, 0.0100f, 0.0214f, 0.0412f, 0.0711f, 0.1106f, 0.1566f, 0.2068f, 0.2594f, 0.3139f, 0.3680f, 0.4211f, 0.4733f, 0.5233f, 0.5720f, 0.6192f, 0.6649f, 0.7087f, 0.7495f, 0.7863f, 0.8196f, 0.8500f, 0.8773f, 0.9021f, 0.9234f, 0.9412f, 0.9564f, 0.9690f, 0.9795f, 0.9880f}},
    /* Sony: mean of 65 "Camera Standard" profiles */
    {"Sony", {0.0000f, 0.0010f, 0.0025f, 0.0057f, 0.0119f, 0.0227f, 0.0403f, 0.0642f, 0.0978f, 0.1403f, 0.1872f, 0.2364f, 0.2886f, 0.3460f, 0.4035f, 0.4608f, 0.5155f, 0.5663f, 0.6137f, 0.6605f, 0.7078f, 0.7503f, 0.7850f, 0.8172f, 0.8473f, 0.8730f, 0.8927f, 0.9094f, 0.9246f, 0.9386f, 0.9494f, 0.9581f, 0.9658f}},
    /* Panasonic: mean of 41 "Camera Standard" profiles */
    {"Panasonic", {0.0000f, 0.0005f, 0.0020f, 0.0050f, 0.0120f, 0.0256f, 0.0482f, 0.0782f, 0.1158f, 0.1589f, 0.2062f, 0.2560f, 0.3086f, 0.3613f, 0.4137f, 0.4657f, 0.5170f, 0.5675f, 0.6158f, 0.6612f, 0.7020f, 0.7402f, 0.7742f, 0.8059f, 0.8356f, 0.8640f, 0.8903f, 0.9129f, 0.9324f, 0.9492f, 0.9645f, 0.9789f, 0.9882f}},
    /* Olympus: mean of 49 "Camera Natural" profiles */
    {"Olympus", {0.0000f, 0.0002f, 0.0008f, 0.0023f, 0.0072f, 0.0168f, 0.0324f, 0.0552f, 0.0896f, 0.1336f, 0.1845f, 0.2359f, 0.2920f, 0.3499f, 0.4094f, 0.4704f, 0.5296f, 0.5827f, 0.6316f, 0.6733f, 0.7141f, 0.7484f, 0.7773f, 0.8046f, 0.8283f, 0.8498f, 0.8706f, 0.8912f, 0.9097f, 0.9255f, 0.9385f, 0.9507f, 0.9615f}},
    /* Pentax: mean of 4 "Camera Standard" profiles */
    {"Pentax", {0.0000f, 0.0023f, 0.0053f, 0.0106f, 0.0196f, 0.0324f, 0.0500f, 0.0731f, 0.1023f, 0.1379f, 0.1805f, 0.2288f, 0.2808f, 0.3354f, 0.3918f, 0.4488f, 0.5058f, 0.5620f, 0.6164f, 0.6687f, 0.7178f, 0.7638f, 0.8062f, 0.8440f, 0.8769f, 0.9052f, 0.9295f, 0.9498f, 0.9666f, 0.9799f, 0.9897f, 0.9964f, 1.0000f}},
    /* Ricoh: mean of 6 "Camera Standard" profiles */
    {"Ricoh", {0.0000f, 0.0006f, 0.0022f, 0.0054f, 0.0126f, 0.0265f, 0.0476f, 0.0799f, 0.1194f, 0.1634f, 0.2099f, 0.2579f, 0.3100f, 0.3596f, 0.4110f, 0.4620f, 0.5108f, 0.5647f, 0.6172f, 0.6674f, 0.7165f, 0.7603f, 0.8040f, 0.8513f, 0.8994f, 0.9408f, 0.9841f, 1.0000f, 1.0000f, 1.0000f, 1.0000f, 1.0000f, 1.0000f}},
    /* Leica: mean of 7 "Camera Standard" profiles */
    {"Leica", {0.0000f, 0.0011f, 0.0031f, 0.0068f, 0.0152f, 0.0275f, 0.0458f, 0.0684f, 0.0974f, 0.1327f, 0.1726f, 0.2174f, 0.2645f, 0.3153f, 0.3672f, 0.4080f, 0.4450f, 0.4828f, 0.5195f, 0.5559f, 0.5906f, 0.6245f, 0.6560f, 0.6876f, 0.7199f, 0.7531f, 0.7864f, 0.8210f, 0.8553f, 0.8895f, 0.9245f, 0.9599f, 0.9942f}},
    /* Sigma: mean of 3 "Camera Standard" profiles */
    {"Sigma", {0.0000f, 0.0003f, 0.0018f, 0.0047f, 0.0090f, 0.0175f, 0.0315f, 0.0515f, 0.0770f, 0.1105f, 0.1529f, 0.1995f, 0.2499f, 0.3012f, 0.3540f, 0.4087f, 0.4654f, 0.5233f, 0.5775f, 0.6302f, 0.6815f, 0.7309f, 0.7779f, 0.8217f, 0.8612f, 0.8944f, 0.9176f, 0.9397f, 0.9597f, 0.9764f, 0.9885f, 0.9950f, 0.9994f}},
};

} // namespace CameraCurveData

#endif // CAMERACURVEDATA_H
