#!/usr/bin/env python3
"""
Generate Develop/baselineexposuredata.h -- Adobe's per-camera BaselineExposure (EV).

Lightroom / Camera Raw brightens every raw by a per-camera BaselineExposure before the
tone curve (dng_render.cpp: the exposure ramp is Exposure + TotalBaselineExposure). For a
DNG it is tag 50730; for a vendor raw it lives in Adobe's camera database, which is not
readable -- but Adobe DNG Converter writes it into every DNG it makes. So: find one raw per
camera model under the given folders, convert it, and read UniqueCameraModel (the same
maker-prefixed key Winnow's canonical camera model and the DCP lookup use) and
BaselineExposure back out.

Needs exiftool and Adobe DNG Converter (a CURRENT version -- an old one rejects newer
bodies). Tool-time only; Winnow itself never runs either.

Usage: python3 tools/gen_baseline_exposure.py <folder>... > Develop/baselineexposuredata.h
"""
import os
import shutil
import subprocess
import sys
import tempfile

CONVERTER = "/Applications/Adobe DNG Converter.app/Contents/MacOS/Adobe DNG Converter"
RAW_EXT = {".arw", ".nef", ".nrw", ".cr2", ".cr3", ".crw", ".orf", ".raf", ".rw2",
           ".pef", ".srw", ".dng", ".3fr", ".iiq", ".x3f", ".erf", ".mrw", ".rwl"}


def exif(paths, *tags):
    out = subprocess.run(["exiftool", "-s3", "-f", "-T"] + ["-" + t for t in tags] + paths,
                         capture_output=True, text=True).stdout
    return [line.split("\t") for line in out.splitlines()]


def main():
    files = []
    for root in sys.argv[1:]:
        for d, _, names in os.walk(root):
            files += [os.path.join(d, n) for n in names
                      if os.path.splitext(n)[1].lower() in RAW_EXT]
    seen = {}
    for i in range(0, len(files), 200):
        chunk = files[i:i + 200]
        for path, row in zip(chunk, exif(chunk, "Make", "Model")):
            key = tuple(row)
            if "-" not in key and key not in seen:
                seen[key] = path
    table = {}
    with tempfile.TemporaryDirectory() as tmp:
        for (make, model), path in sorted(seen.items()):
            ext = os.path.splitext(path)[1].upper()
            if ext == ".DNG":
                dng = path                      # already carries the tag
            else:
                # Upper-case extension: the converter rejects some lower-case ones.
                src = os.path.join(tmp, "src" + ext)
                shutil.copyfile(path, src)
                dng = os.path.join(tmp, "src.dng")
                if os.path.exists(dng):
                    os.remove(dng)
                subprocess.run([CONVERTER, "-c", "-p0", "-d", tmp, src],
                               capture_output=True, text=True)
            if not os.path.exists(dng):
                print(f"skipped (converter refused): {make} {model}", file=sys.stderr)
                continue
            r = exif([dng], "UniqueCameraModel", "BaselineExposure")
            if not r or r[0][1] == "-":
                print(f"skipped (no BaselineExposure): {make} {model}", file=sys.stderr)
                continue
            table[r[0][0]] = float(r[0][1])
    p = print
    p("#ifndef BASELINEEXPOSUREDATA_H")
    p("#define BASELINEEXPOSUREDATA_H")
    p("")
    p("/*")
    p("    GENERATED by tools/gen_baseline_exposure.py -- do not edit by hand; re-run it")
    p("    over a folder holding a sample of any new body.")
    p("")
    p("    Adobe's per-camera BaselineExposure (EV), read from DNGs that Adobe DNG Converter")
    p("    made of one sample per model, keyed on the DNG's UniqueCameraModel -- the same")
    p("    maker-prefixed key as Winnow's canonical camera model. See Develop/")
    p("    baselineexposure.h.")
    p("*/")
    p("")
    p("namespace BaselineExposureData {")
    p("")
    p("struct Entry { const char *model; float ev; };")
    p("")
    p("constexpr Entry kTable[] = {")
    for model, ev in sorted(table.items()):
        p(f'    {{"{model}", {ev:.2f}f}},')
    p("};")
    p("")
    p("} // namespace BaselineExposureData")
    p("")
    p("#endif // BASELINEEXPOSUREDATA_H")


if __name__ == "__main__":
    main()
