#!/usr/bin/env python3
"""
Generate Develop/cameracurvedata.h -- the per-maker "Camera contrast" tone curves.

For each maker, every installed Adobe camera-matching profile of that maker's plain style
("Camera Standard"; Olympus/OM have no Standard, so "Camera Natural") is read, its
ProfileToneCurve is composed with its BaselineExposureOffset -- C(2^BEO * x), so the table
maps SCENE-linear input directly -- and the curves are averaged sample by sample. GENERIC,
the fallback for a maker with no profiles (Fujifilm, unknown bodies), is the mean of
Canon, Nikon and Sony.

Only the 0..1 part of each curve is kept, and Winnow uses it only up to its knee: above
that, Develop/cameracurve.h replaces the camera's own shoulder with a roll-off that keeps
rising past white (see the header there).

Usage:  python3 tools/gen_camera_curves.py [profile-root] > Develop/cameracurvedata.h
Default root: /Library/Application Support/Adobe/CameraRaw/CameraProfiles/Camera
"""
import bisect
import glob
import os
import struct
import sys

ROOT = "/Library/Application Support/Adobe/CameraRaw/CameraProfiles/Camera"
N = 33                                   # samples; x = (i/32)^2 puts half of them in the
GRID = [(i / (N - 1)) ** 2 for i in range(N)]   # bottom quarter, where curves bend most

# maker key -> (folder first-words, style)
MAKERS = [
    ("Canon",     ("Canon",),          "Standard"),
    ("Nikon",     ("Nikon",),          "Standard"),
    ("Sony",      ("Sony",),           "Standard"),
    ("Panasonic", ("Panasonic",),      "Standard"),
    ("Olympus",   ("Olympus", "OM"),   "Natural"),
    ("Pentax",    ("Pentax",),         "Standard"),
    ("Ricoh",     ("Ricoh",),          "Standard"),
    ("Leica",     ("Leica",),          "Standard"),
    ("Sigma",     ("Sigma", "SIGMA"),  "Standard"),
]


def dcp_tags(path):
    b = open(path, "rb").read()
    e = "<" if b[:2] == b"II" else ">"
    off = struct.unpack(e + "I", b[4:8])[0]
    n = struct.unpack(e + "H", b[off:off + 2])[0]
    out = {}
    for i in range(n):
        t, ty, cnt, vo = struct.unpack(e + "HHII", b[off + 2 + 12 * i:off + 14 + 12 * i])
        size = {1: 1, 2: 1, 3: 2, 4: 4, 5: 8, 7: 1, 9: 4, 10: 8, 11: 4, 12: 8}.get(ty, 1) * cnt
        data = b[off + 10 + 12 * i:off + 14 + 12 * i] if size <= 4 else b[vo:vo + size]
        if ty == 11:
            out[t] = struct.unpack(e + "%df" % cnt, data)
        elif ty == 10:
            v = struct.unpack(e + "%di" % (2 * cnt), data)
            out[t] = [v[k] / v[k + 1] for k in range(0, len(v), 2)]
        elif ty == 2:
            out[t] = data.rstrip(b"\0").decode("latin1")
    return out


def interp(xs, ys, x):
    if x <= xs[0]:
        return ys[0]
    if x >= xs[-1]:
        return ys[-1]
    i = bisect.bisect_right(xs, x)
    t = (x - xs[i - 1]) / (xs[i] - xs[i - 1])
    return ys[i - 1] + (ys[i] - ys[i - 1]) * t


def maker_curve(root, folders, style):
    curves = []
    for f in glob.glob(os.path.join(root, "*", "*.dcp")):
        if os.path.basename(os.path.dirname(f)).split()[0] not in folders:
            continue
        t = dcp_tags(f)
        if t.get(50936, "") != "Camera " + style or 50940 not in t:
            continue
        c = t[50940]
        xs, ys = list(c[0::2]), list(c[1::2])
        g = 2.0 ** t.get(51109, [0.0])[0]
        curves.append([interp(xs, ys, g * x) for x in GRID])
    if not curves:
        return None, 0
    return [sum(c[i] for c in curves) / len(curves) for i in range(N)], len(curves)


def main():
    root = sys.argv[1] if len(sys.argv) > 1 else ROOT
    rows = []
    for key, folders, style in MAKERS:
        y, n = maker_curve(root, folders, style)
        if y:
            rows.append((key, style, n, y))
    big3 = [r[3] for r in rows if r[0] in ("Canon", "Nikon", "Sony")]
    generic = [sum(c[i] for c in big3) / len(big3) for i in range(N)]

    p = print
    p("#ifndef CAMERACURVEDATA_H")
    p("#define CAMERACURVEDATA_H")
    p("")
    p("/*")
    p("    GENERATED by tools/gen_camera_curves.py -- do not edit by hand; re-run it.")
    p("")
    p("    Per-maker average tone curves for the \"Camera contrast\" tone mapping, from the")
    p("    installed Adobe camera-matching profiles (each curve composed with its profile's")
    p("    BaselineExposureOffset, so x is scene-linear with 1.0 = sensor white). Sampled at")
    p("    x = (i/32)^2. See Develop/cameracurve.h for how they are used.")
    p("*/")
    p("")
    p("namespace CameraCurveData {")
    p("")
    p("constexpr int kSamples = %d;" % N)
    p("")
    p("struct Maker { const char *name; float y[kSamples]; };")
    p("")
    p("/* Generic: mean of Canon, Nikon and Sony -- for any maker not listed below. */")
    p("constexpr float kGeneric[kSamples] = {")
    p("    " + ", ".join("%.4ff" % v for v in generic))
    p("};")
    p("")
    p("constexpr Maker kMakers[] = {")
    for key, style, n, y in rows:
        p("    /* %s: mean of %d \"Camera %s\" profiles */" % (key, n, style))
        p("    {\"%s\", {%s}}," % (key, ", ".join("%.4ff" % v for v in y)))
    p("};")
    p("")
    p("} // namespace CameraCurveData")
    p("")
    p("#endif // CAMERACURVEDATA_H")


if __name__ == "__main__":
    main()
