/*
    LutParse -- reading .cube and HaldCLUT into a Lut3d::Table.

    WHY THIS TEST EXISTS. Both formats are a flat run of numbers whose MEANING is entirely
    in the index convention, and getting that convention wrong does not fail -- it renders
    a plausible picture with red and blue exchanged, or a table sheared along one axis.
    Neither shows up as an error anywhere.

    So the index order is proved twice, by two arguments that do not share an assumption:

      o an eight-corner 2x2x2 .cube, where each corner is a distinct primary, so a
        transposition moves a known colour to a known wrong place;
      o CROSS-FORMAT AGREEMENT -- one analytic look emitted as BOTH a .cube and a Hald
        image from the same generator, required to agree. The two formats are written by
        different code down different paths, so a transposition in either reader alone
        cannot pass, and a transposition in both would have to be the same transposition.

    The rest is refusal: every malformed file must be rejected WITH A REASON rather than
    padded, because these are untrusted downloads and a silently zero-filled table is a
    black picture nobody can explain.
*/

#include <QtTest>
#include <QDir>
#include <QFile>
#include <QImage>
#include <algorithm>
#include <cmath>

#include "Develop/lutparse.h"

class TstLutParse : public QObject
{
    Q_OBJECT

private slots:
    void cubeParsesAllTheSyntax();
    void cubeCornerOrderIsRedFastest();
    void cubeRejects_data();
    void cubeRejects();
    void cubeOneDimensional();
    void haldIdentityRoundTrips_data();
    void haldIdentityRoundTrips();
    void haldSixteenBitRoundTrips();
    void haldRejects_data();
    void haldRejects();
    void cubeAndHaldAgree();
    void realWorldCubesParse();
};

/* ---------------------------------------------------------------------------------------
   The look used by the cross-format test: channel mixing plus a per-channel curve, so it
   is neither symmetric nor separable -- a transposition cannot hide in it.
   ------------------------------------------------------------------------------------ */
static void look(float r, float g, float b, float &orr, float &og, float &ob)
{
    orr = std::min(1.0f, std::max(0.0f, 0.90f * r + 0.10f * g));
    og  = std::min(1.0f, std::max(0.0f, std::pow(g, 1.10f)));
    ob  = std::min(1.0f, std::max(0.0f, 0.80f * b + 0.20f * r));
}

/* The same look as .cube text: n^3 triplets, red fastest. */
static QByteArray asCube(int n)
{
    QByteArray out = "# generated by the test\nTITLE \"Agreement\"\n";
    out += "LUT_3D_SIZE " + QByteArray::number(n) + "\n";
    const float d = float(n - 1);
    for (int b = 0; b < n; ++b)
        for (int g = 0; g < n; ++g)
            for (int r = 0; r < n; ++r) {
                float x, y, z;
                look(float(r) / d, float(g) / d, float(b) / d, x, y, z);
                out += QByteArray::number(double(x), 'f', 6) + " " +
                       QByteArray::number(double(y), 'f', 6) + " " +
                       QByteArray::number(double(z), 'f', 6) + "\n";
            }
    return out;
}

/* The same look as a HaldCLUT image of the given level: w = L^3, cube = L^2. */
static QImage asHald(int level)
{
    const int size = level * level;
    const int w = level * level * level;
    QImage img(w, w, QImage::Format_RGB888);
    const float d = float(size - 1);
    size_t k = 0;
    for (int y = 0; y < w; ++y) {
        uchar *p = img.scanLine(y);
        for (int x = 0; x < w; ++x, ++k) {
            const int r = int(k % size_t(size));
            const int g = int((k / size_t(size)) % size_t(size));
            const int b = int(k / (size_t(size) * size_t(size)));
            float ox, oy, oz;
            look(float(r) / d, float(g) / d, float(b) / d, ox, oy, oz);
            p[x * 3 + 0] = uchar(std::lround(ox * 255.0f));
            p[x * 3 + 1] = uchar(std::lround(oy * 255.0f));
            p[x * 3 + 2] = uchar(std::lround(oz * 255.0f));
        }
    }
    return img;
}

/* An identity Hald of the given level. */
static QImage identityHald(int level)
{
    const int size = level * level;
    const int w = level * level * level;
    QImage img(w, w, QImage::Format_RGB888);
    const float d = float(size - 1);
    size_t k = 0;
    for (int y = 0; y < w; ++y) {
        uchar *p = img.scanLine(y);
        for (int x = 0; x < w; ++x, ++k) {
            const int r = int(k % size_t(size));
            const int g = int((k / size_t(size)) % size_t(size));
            const int b = int(k / (size_t(size) * size_t(size)));
            p[x * 3 + 0] = uchar(std::lround(float(r) / d * 255.0f));
            p[x * 3 + 1] = uchar(std::lround(float(g) / d * 255.0f));
            p[x * 3 + 2] = uchar(std::lround(float(b) / d * 255.0f));
        }
    }
    return img;
}

/* ---------------------------------------------------------------------------------------
   Cases
   ------------------------------------------------------------------------------------ */

void TstLutParse::cubeParsesAllTheSyntax()
{
    /* Everything a real file throws at the reader at once: a leading comment, a quoted
       title, a trailing comment on a keyword line, CRLF, tabs, blank lines, a domain,
       and keywords appearing AFTER data has started. */
    const QByteArray text =
        "# Copyright nobody\r\n"
        "TITLE \"Test Look\"\r\n"
        "\r\n"
        "LUT_3D_SIZE 2   # the size\r\n"
        "DOMAIN_MIN 0.0 0.0 0.0\r\n"
        "\t0.0 0.0 0.0\r\n"
        "1.0 0.0 0.0\r\n"
        "DOMAIN_MAX 1.0 1.0 1.0\r\n"
        "0.0 1.0 0.0\r\n"
        "1.0 1.0 0.0\r\n"
        "0.0 0.0 1.0\r\n"
        "1.0 0.0 1.0\r\n"
        "0.0 1.0 1.0\r\n"
        "1.0 1.0 1.0\r\n"
        "\r\n";
    Lut3d::Table t;
    QString err;
    QVERIFY2(LutParse::ParseCube(text, t, &err), qPrintable(err));
    QVERIFY(err.isEmpty());
    QCOMPARE(t.size, 2);
    QCOMPARE(QString::fromStdString(t.title), QString("Test Look"));
    QVERIFY(t.is3D());
    QCOMPARE(t.v.size(), size_t(8 * 3));
    QCOMPARE(t.domainMin[0], 0.0f);
    QCOMPARE(t.domainMax[2], 1.0f);
}

void TstLutParse::cubeCornerOrderIsRedFastest()
{
    /*
        THE ORDER PROOF. Eight corners, each the identity, written in the order the spec
        says: red fastest. If the reader transposed red and blue, the entry reached by a
        pure-red input would be the one written for pure blue, and this fails.
    */
    const QByteArray text =
        "LUT_3D_SIZE 2\n"
        "0 0 0\n"      // r=0 g=0 b=0
        "1 0 0\n"      // r=1 g=0 b=0
        "0 1 0\n"      // r=0 g=1 b=0
        "1 1 0\n"
        "0 0 1\n"      // r=0 g=0 b=1
        "1 0 1\n"
        "0 1 1\n"
        "1 1 1\n";
    Lut3d::Table t;
    QVERIFY(LutParse::ParseCube(text, t));

    struct { float in[3]; float want[3]; } probes[] = {
        {{1, 0, 0}, {1, 0, 0}},
        {{0, 1, 0}, {0, 1, 0}},
        {{0, 0, 1}, {0, 0, 1}},
        {{1, 1, 0}, {1, 1, 0}},
        {{0, 0, 0}, {0, 0, 0}},
        {{1, 1, 1}, {1, 1, 1}},
    };
    for (const auto &p : probes) {
        float r = p.in[0], g = p.in[1], b = p.in[2];
        Lut3d::Apply(t, r, g, b);
        QVERIFY2(std::fabs(r - p.want[0]) < 1e-6f &&
                 std::fabs(g - p.want[1]) < 1e-6f &&
                 std::fabs(b - p.want[2]) < 1e-6f,
                 qPrintable(QString("(%1,%2,%3) -> (%4,%5,%6), wanted (%7,%8,%9)")
                                .arg(p.in[0]).arg(p.in[1]).arg(p.in[2])
                                .arg(r).arg(g).arg(b)
                                .arg(p.want[0]).arg(p.want[1]).arg(p.want[2])));
    }
}

void TstLutParse::cubeRejects_data()
{
    QTest::addColumn<QByteArray>("text");
    QTest::newRow("no size")
        << QByteArray("0 0 0\n1 1 1\n");
    QTest::newRow("one triplet short")
        << QByteArray("LUT_3D_SIZE 2\n0 0 0\n1 0 0\n0 1 0\n1 1 0\n0 0 1\n1 0 1\n0 1 1\n");
    QTest::newRow("one triplet long")
        << QByteArray("LUT_3D_SIZE 2\n0 0 0\n1 0 0\n0 1 0\n1 1 0\n0 0 1\n1 0 1\n"
                      "0 1 1\n1 1 1\n0.5 0.5 0.5\n");
    QTest::newRow("nan")
        << QByteArray("LUT_3D_SIZE 2\n0 0 0\n1 0 0\n0 1 0\n1 1 0\n0 0 1\n1 0 1\n"
                      "0 1 1\nnan 1 1\n");
    QTest::newRow("size 1")        << QByteArray("LUT_3D_SIZE 1\n0 0 0\n");
    QTest::newRow("size 300")      << QByteArray("LUT_3D_SIZE 300\n0 0 0\n");
    QTest::newRow("two sizes")     << QByteArray("LUT_3D_SIZE 2\nLUT_1D_SIZE 2\n");
    QTest::newRow("degenerate domain")
        << QByteArray("LUT_3D_SIZE 2\nDOMAIN_MIN 1 1 1\nDOMAIN_MAX 1 1 1\n"
                      "0 0 0\n1 0 0\n0 1 0\n1 1 0\n0 0 1\n1 0 1\n0 1 1\n1 1 1\n");
    QTest::newRow("binary garbage")
        << QByteArray("\x00\x01\x02\xff\xfe rubbish \x7f", 22);
    QTest::newRow("empty")         << QByteArray();
}

void TstLutParse::cubeRejects()
{
    QFETCH(QByteArray, text);
    Lut3d::Table t;
    QString err;
    QVERIFY2(!LutParse::ParseCube(text, t, &err), "a malformed cube was accepted");
    QVERIFY2(!err.isEmpty(), "a rejection came back with no reason");
    QVERIFY2(t.isEmpty(), "a rejected cube left a usable table behind");
}

void TstLutParse::cubeOneDimensional()
{
    const QByteArray text =
        "LUT_1D_SIZE 2\n"
        "1.0 0.0 0.0\n"
        "0.0 1.0 0.5\n";
    Lut3d::Table t;
    QString err;
    QVERIFY2(LutParse::ParseCube(text, t, &err), qPrintable(err));
    QVERIFY(t.is1D());
    QVERIFY(!t.is3D());
    float r = 0.25f, g = 0.25f, b = 0.25f;
    Lut3d::Apply(t, r, g, b);
    QVERIFY(std::fabs(r - 0.75f) < 1e-6f);
    QVERIFY(std::fabs(g - 0.25f) < 1e-6f);
    QVERIFY(std::fabs(b - 0.125f) < 1e-6f);
}

void TstLutParse::haldIdentityRoundTrips_data()
{
    QTest::addColumn<int>("level");
    QTest::newRow("level 2 (8x8, 4-cube)")     << 2;
    QTest::newRow("level 4 (64x64, 16-cube)")  << 4;
    QTest::newRow("level 8 (512x512, 64-cube)")<< 8;
}

void TstLutParse::haldIdentityRoundTrips()
{
    QFETCH(int, level);
    Lut3d::Table t;
    QString err;
    QVERIFY2(LutParse::FromHald(identityHald(level), t, &err), qPrintable(err));
    QCOMPARE(t.size, level * level);

    /* Identity to within 8-bit quantisation, off-lattice as well as on. */
    for (int i = 0; i <= 40; ++i)
        for (int j = 0; j <= 40; ++j) {
            const float x = float(i) / 40.0f, y = float(j) / 40.0f, z = 1.0f - x;
            float r = x, g = y, b = z;
            Lut3d::Apply(t, r, g, b);
            QVERIFY2(std::fabs(r - x) < 1.5f / 255.0f &&
                     std::fabs(g - y) < 1.5f / 255.0f &&
                     std::fabs(b - z) < 1.5f / 255.0f,
                     qPrintable(QString("identity Hald moved (%1,%2,%3) to (%4,%5,%6)")
                                    .arg(x).arg(y).arg(z).arg(r).arg(g).arg(b)));
        }
}

void TstLutParse::haldSixteenBitRoundTrips()
{
    /* 16-bit is accepted because QImage gives it free and the precision is real. */
    const int level = 4, size = level * level, w = level * level * level;
    QImage img(w, w, QImage::Format_RGBX64);
    const float d = float(size - 1);
    size_t k = 0;
    for (int y = 0; y < w; ++y) {
        quint16 *p = reinterpret_cast<quint16 *>(img.scanLine(y));
        for (int x = 0; x < w; ++x, ++k) {
            const int r = int(k % size_t(size));
            const int g = int((k / size_t(size)) % size_t(size));
            const int b = int(k / (size_t(size) * size_t(size)));
            p[x * 4 + 0] = quint16(std::lround(float(r) / d * 65535.0f));
            p[x * 4 + 1] = quint16(std::lround(float(g) / d * 65535.0f));
            p[x * 4 + 2] = quint16(std::lround(float(b) / d * 65535.0f));
            p[x * 4 + 3] = 65535;
        }
    }
    Lut3d::Table t;
    QString err;
    QVERIFY2(LutParse::FromHald(img, t, &err), qPrintable(err));
    QCOMPARE(t.size, size);
    float r = 0.5f, g = 0.25f, b = 0.75f;
    Lut3d::Apply(t, r, g, b);
    QVERIFY(std::fabs(r - 0.5f)  < 1.5f / 65535.0f);
    QVERIFY(std::fabs(g - 0.25f) < 1.5f / 65535.0f);
    QVERIFY(std::fabs(b - 0.75f) < 1.5f / 65535.0f);
}

void TstLutParse::haldRejects_data()
{
    QTest::addColumn<QImage>("img");
    QTest::newRow("null")       << QImage();
    QTest::newRow("not square") << QImage(64, 32, QImage::Format_RGB888);
    /* 100 is not a perfect cube, so no integer level produces it. */
    QTest::newRow("width not a cube") << QImage(100, 100, QImage::Format_RGB888);
    QTest::newRow("1x1")        << QImage(1, 1, QImage::Format_RGB888);
    /* Level 16 would be a 256-cube, past Lut3d::kMaxSize. */
    QTest::newRow("too large")  << QImage(4096, 4096, QImage::Format_RGB888);
}

void TstLutParse::haldRejects()
{
    QFETCH(QImage, img);
    Lut3d::Table t;
    QString err;
    QVERIFY2(!LutParse::FromHald(img, t, &err), "a malformed Hald was accepted");
    QVERIFY2(!err.isEmpty(), "a rejection came back with no reason");
    QVERIFY(t.isEmpty());
}

void TstLutParse::cubeAndHaldAgree()
{
    /*
        THE CROSS-FORMAT PROOF. One look, two encoders, two readers. Level 8 and
        LUT_3D_SIZE 64 describe the same 64-cube, so every lattice entry must match --
        and since the two files are written by different code and read by different code,
        an index transposition in either reader alone cannot survive this.
    */
    const int level = 8, n = level * level;
    Lut3d::Table fromCube, fromHald;
    QString err;
    QVERIFY2(LutParse::ParseCube(asCube(n), fromCube, &err), qPrintable(err));
    QVERIFY2(LutParse::FromHald(asHald(level), fromHald, &err), qPrintable(err));
    QCOMPARE(fromCube.size, n);
    QCOMPARE(fromHald.size, n);
    QCOMPARE(fromCube.v.size(), fromHald.v.size());

    /* Every lattice entry, within 8-bit quantisation -- the Hald's limit, not the
       cube's. */
    float worst = 0.0f;
    for (size_t i = 0; i < fromCube.v.size(); ++i)
        worst = std::max(worst, std::fabs(fromCube.v[i] - fromHald.v[i]));
    QVERIFY2(worst < 1.5f / 255.0f,
             qPrintable(QString("lattice entries differ by up to %1").arg(worst)));

    /* And off-lattice, which also exercises the sampler through both tables. */
    worst = 0.0f;
    for (int i = 0; i < 200; ++i) {
        const float x = float((i * 37) % 101) / 100.0f;
        const float y = float((i * 61) % 101) / 100.0f;
        const float z = float((i * 17) % 101) / 100.0f;
        float ar = x, ag = y, ab = z;
        float br = x, bg = y, bb = z;
        Lut3d::Apply(fromCube, ar, ag, ab);
        Lut3d::Apply(fromHald, br, bg, bb);
        worst = std::max({worst, std::fabs(ar - br), std::fabs(ag - bg),
                          std::fabs(ab - bb)});
    }
    QVERIFY2(worst < 2.5f / 255.0f,
             qPrintable(QString("off-lattice samples differ by up to %1").arg(worst)));

    /* The look is not the identity, or none of the above would mean anything. */
    float r = 0.2f, g = 0.8f, b = 0.4f;
    Lut3d::Apply(fromCube, r, g, b);
    QVERIFY2(std::fabs(r - 0.2f) > 0.01f || std::fabs(b - 0.4f) > 0.01f,
             "the agreement look is too close to the identity to prove anything");
}

/*
    OPPORTUNISTIC, and the only case here that sees a file somebody else wrote. Every
    fixture above is built in this source, which proves the reader against what the spec
    SAYS; this proves it against what tools actually emit -- Adobe's own exported LUTs,
    with their comment headers, DOMAIN lines and 6-decimal formatting. It skips where
    those files are not installed, exactly as tst_cameraprofilestore skips without
    profiles.
*/
void TstLutParse::realWorldCubesParse()
{
    const QStringList roots = {
        "/Applications/Adobe Photoshop 2026/Presets/3DLUTs",
        "/Applications/Adobe Photoshop (Beta)/Presets/3DLUTs",
        "/Applications/Adobe Photoshop 2025/Presets/3DLUTs",
    };
    QStringList files;
    for (const QString &r : roots) {
        QDir d(r);
        if (!d.exists()) continue;
        for (const QString &f : d.entryList({"*.cube", "*.CUBE"}, QDir::Files))
            files << d.filePath(f);
    }
    if (files.isEmpty()) QSKIP("no real .cube files installed on this machine");

    int parsed = 0;
    for (const QString &path : files) {
        QFile f(path);
        QVERIFY(f.open(QIODevice::ReadOnly));
        Lut3d::Table t;
        QString err;
        QVERIFY2(LutParse::ParseCube(f.readAll(), t, &err),
                 qPrintable(QString("%1: %2").arg(QFileInfo(path).fileName(), err)));
        QVERIFY2(t.isValid(), qPrintable(path));
        /* A real look must move colour somewhere, and must stay finite doing it. */
        float r = 0.3f, g = 0.55f, b = 0.72f;
        Lut3d::Apply(t, r, g, b);
        QVERIFY(std::isfinite(r) && std::isfinite(g) && std::isfinite(b));
        ++parsed;
    }
    qInfo("parsed %d real .cube files", parsed);
    QVERIFY(parsed > 0);
}

QTEST_MAIN(TstLutParse)
#include "tst_lutparse.moc"
